### PR TITLE
Detect duplicates in `QuantumCircuit.compose`

### LINKED ISSUE #4970: QuantumCircuit.compose does not raise an error with invalid qubits argument
### Information

- **Qiskit Terra version**: master @ b1c9a23
- **Python version**: 3.7.1
- **Operating system**: osx

### What is the current behavior?
`QuantumCircuit.compose` runs normally if `qubits` argument has duplicate values. If you try to compose two circuits after converting to dag, `DAGCircuit.compose` raises an error. Introduced after #4762 .

### Steps to reproduce the problem
```
n = 3
qc = QuantumCircuit(n)
qc.h(range(n))

m = 2
circ = QuantumCircuit(m)
circ.z(range(m))
circ.cx(0, 1)

new_circuit = qc.compose(circ, qubits=[1, 1])
print(new_circuit)


     ┌───┐          
q_0: ┤ H ├──────────
     ├───┤┌───┐┌───┐
q_1: ┤ H ├┤ Z ├┤ Z ├
     ├───┤└───┘└───┘
q_2: ┤ H ├──────────
     └───┘   
```

But 
```
dag_qc   = circuit_to_dag(qc)
dag_circ = circuit_to_dag(circ)

dag = dag_qc.compose(dag_circ, 
                     qubits=[1, 1], inplace=False)


raises DAGCircuitError
```

### What is the expected behavior?
As duplicate values in `qubits` is not a valid input, `QuantumCircuit.compose` should raise an error.

### Suggested solutions
Similar to `DAGCircuit.compose`
```
        # Check the edge_map for duplicate values
        if len(set(edge_map.values())) != len(edge_map):
              raise CircuitError("duplicates in wire_map")
```

### PR DESCRIPTION
**Pull request by jakelishman**
### Summary

Previously, `QuantumCircuit.compose` would silently attempt to compose multiple qubits onto the same state, which would fail in weird ways if any multi-qubit instructions were acting on these collapsed qubits.

### Details and comments

Fix #4970.

### CODE REVIEW

**Review by Cryoris — DISMISSED** [review]
LGTM, now the raised error makes a lot more sense 👍🏻

**Comment by jakelishman** [comment]
In retrospect, I'll remove this from "stable backport", because the bug's been open for ages without huge complaints, and we're close to 1.0 anyway, so there's little need to increase the risk of the 0.45.2 release.

**Comment by jakelishman** [comment]
The new test here caught a sort-of bug in #11214 where there was an early return for empty `data` in the composed operation without checking the qubits and clbits (the errors weren't raised).  Alone that's not _much_ of a problem, but the bigger issue that it turned up was that global-phase and calibrations were added to the `dest` circuit _before_ error checking, which meant that if the composition raised an exception, we could be leaving the `dest` in an partially mutated state, which could cause issues for circuit-reuse after exception handling if we were doing an in-place composition.

**Comment by Cryoris** [comment]
Nice catch 👍🏻 there seem to be some other modifications to `dest` happening before, such as changing the `dt` unit and the `duration`. Should we make sure these are also modified only after the check?

**Comment by jakelishman** [comment]
The `duration` and `unit` question came up in #11214 and the result was a resounding "uh" - we don't really know what those are for at a circuit level, nor what meaning they're supposed to have (what if a circuit is made of incompatible durations with incompatible `unit`s?).

Seems easy enough to change, at any rate - done in 48116a.  While it appears like I moved it after some possible return paths, those return paths all (necessarily) call `QuantumCircuit.append`, which will zero out the duration and unit as well.

**Review by Cryoris — APPROVED** [review]
LGTM thanks for the updates!

**Pull request merged**
