### PR TITLE
Support ECR gates in `Pauli.evolve(QuantumCircuit)`

### LINKED ISSUE #12086: `Pauli.evolve()` should recognize ECR gates as Clifford gates
### Environment

- **Qiskit version**: 1.0.2
- **Python version**: 3.11
- **Operating system**: macos

### What is happening?

```
qc = QuantumCircuit(2)
qc.ecr(0,1)
qi.Pauli('XX').evolve(qc)
```

The above call to evolve() raises an error even though qc contains only Clifford gates:

```
QiskitError: 'Cannot apply Instruction: u'
```

### How can we reproduce the issue?

```
qc = QuantumCircuit(2)
qc.ecr(0,1)
qi.Pauli('XX').evolve(qc)
```

### What should happen?

ECR gates should be recognized as Clifford gates, and the Pauli should evolve successfully.

Related: #12085 

### Any suggestions?

_No response_

### LINKED ISSUE #12093: `Pauli.evolve(qc, frame='s')` will ignore contents of qc for certain values of qc.name
### Environment

- **Qiskit version**: 1.1.0.dev
- **Python version**: 3.11
- **Operating system**: macos

### What is happening?

`base_pauli._append_circuit`, which is a subroutine of `base_pauli.evolve`, first converts a circuit to an instruction, then checks if the name of the instruction matches a list of special-case gates that it recognizes. However if the input circuit has the same name as one of these special gates, then it will match even though its contents are not equal to that gate.

This bug is avoided with the default setting frame='h', because this first takes the inverse of the circuit, such that '_dg' is appended to its name, and none of the special-case gates have names that end in '_dg'.

### How can we reproduce the issue?

Evolution of a Pauli by an empty circuit named 'cx'. 
It's an empty circuit, so nothing should happen, regardless of the chosen frame.
```
qc = QuantumCircuit(2, name='cx')
p = qi.Pauli('IX')
```
Heisenberg frame:
```
p.evolve(qc, frame='h')
```
output (correct):
```
Pauli('IX')
```

Schrodinger frame:
```
p.evolve(qc, frame='s')
```
output (incorrect):
```
Pauli('XX')
```

### What should happen?

It's probably not necessary for `_append_circuit` to convert the circuit to a gate at all, since it is later just unrolled back to a QuantumCircuit according to gate.definition?

### Any suggestions?

_No response_

### PR DESCRIPTION
**Pull request by aeddins-ibm**
### Summary
Should fix #12086 and also #12093.

### CODE REVIEW

**Review by ShellyGarion — COMMENTED** [review]
@aeddins-ibm - thanks for finding these bugs and fixing them!
Could you perhaps add a test that shows that https://github.com/Qiskit/qiskit/issues/12093 is solved? 
Could you also add some release notes?

**Comment by aeddins-ibm** [comment]
Hi @ShellyGarion, I have added a test and also a release note. I haven't written release notes before so just tried to follow what others look like. In particular is it OK that 1) there's no max-characters-per-line in the note, and 2) I just labeled it "fixes" rather than something more specific like "fixes_quantuminfo" (if that's even a thing people write)? Thanks

**Comment by aeddins-ibm** [comment]
The automated tests above failed with the error message
`ERROR: Could not build wheels for qiskit-aer, which is required to install pyproject.toml-based projects`

I don't know if this is somehow caused by this PR, or if it's some unrelated failure. Does anyone have a suggestion how to proceed? The [commit](https://github.com/Qiskit/qiskit/pull/12095/commits/47d93251c5d5395391b99fe1e0ac3be6eab55d8f) where the failure started showing up looks innocuous to me.

**Comment by mtreinish** [comment]
> The automated tests above failed with the error message `ERROR: Could not build wheels for qiskit-aer, which is required to install pyproject.toml-based projects`
> 
> I don't know if this is somehow caused by this PR, or if it's some unrelated failure. Does anyone have a suggestion how to proceed? The [commit](https://github.com/Qiskit/qiskit/pull/12095/commits/47d93251c5d5395391b99fe1e0ac3be6eab55d8f) where the failure started showing up looks innocuous to me.

qiskit-aer released this morning and didn't build wheels (i.e. precompiled binaries) for 3.8 by mistake. I manually retriggered a build for py3.8; assuming that works it should resolve itself soon. If it doesn't then I'll push up a PR to exclude the 0.14.0 release until it can be resolved.

**Comment by mtreinish** [comment]
The manual build for 3.8 on aer completed and the wheels are on pypi now, so I've retriggered the failed job and it should hopefully pass now.

**Review by ShellyGarion — COMMENTED** [review]
Generally, this PR looks good to me.

Perhaps you could also add `ECRGate` to `test_phase_dtype_evolve_clifford` in `test_pauli_list `?

The release notes look fine to me, but I prefer to let someone from Qiskit Core review them too.

**Review by ShellyGarion — DISMISSED** [review]
LGTM, thanks @aeddins-ibm for finding this bug and fixing it!

**Comment by ShellyGarion** [comment]
It seems that now there is a conflict that should be resolved. @aeddins-ibm - could you please handle it?

**Review by ShellyGarion — APPROVED** [review]

**Pull request merged**
