### PR TITLE
Remove examples/ directory

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit removes the examples/ directory from Qiskit. At one time in the past these scripts and qasm files served as a useful example for how to get started with Qiskit. However the patterns shown in these examples aren't very relevant anymore and have been superseded by the official documentation and the numerous tutorials out there now. While these examples still work as we've been running tests to validate they're still functional on every commit, there is little value in keeping them around. This commit removes the examples directory and all the files contained within. The test_examples unittest module is also removed since there is nothing left to test anymore.

### Details and comments

### CODE REVIEW

**Review by Cryoris — COMMENTED** [review]
There might be some other spots mentioning the examples directory, which would be good to remove:
* `CONTRIBUTING.md` mentions `test_examples` in explaining tests
* the `Makefile` also runs the examples, doesn't it?
* the `pyproject.toml` has a `test-command` variable which uses the examples too 🤔

**Comment by mtreinish** [comment]
> * the `pyproject.toml` has a test-command variable which uses the examples too

This should have been fixed by #13205

**Comment by mtreinish** [comment]
> * CONTRIBUTING.md mentions test_examples in explaining tests
> * the Makefile also runs the examples, doesn't it?

Fixed in: https://github.com/Qiskit/qiskit/pull/13218/commits/09365f8ec02766ab7ae681dafbba355b36cb8cff

**Review by Cryoris — APPROVED** [review]
LGTM 👍🏻 It's nice to have less random hits on files one wasn't looking for now 🙂

**Pull request merged**
