### PR TITLE
Make ``iqp`` the matplotlib default style

### PR DESCRIPTION
**Pull request by Cryoris**
### Summary

Following #10950, this PR sets ``"iqp"`` as the new default for the matplotlib drawer.

**Note:** Due to the apparent impossibility of reproducing the precise matplotlib drawings locally I'm abusing the CI to generate the correct images, hence, opening this early draft PR.

### Details and comments

In addition, this PR includes some additional changes
* Using the black-white scheme must explicitly use `style="bw"` instead of `style=False`. This is a suggestion for a more consistent interface, the deprecation would be out into 0.46.
* Refactors the `DefaultStyle` to not hardcode the default colors but load it from a JSON, such as all other color schemes.
* Introduces a `StyleDict`, which is a dictionary handling matplotlib-specific aliases (such as "ec" for "edgecolor") instead of keeping a dictionary with duplicate entries.

### CODE REVIEW

**Review by ElePT — COMMENTED** [review]
LGTM, but there are still a few lint complains to fix. I think that the docs failures might get resolved after merging from main (at least that was the case for a PR I had with the same issues.

**Comment by jakelishman** [comment]
I think the docs failure is local to this PR - the actual errors are these:
```
/home/vsts/work/1/s/.tox/docs/lib/python3.9/site-packages/qiskit/circuit/quantumcircuit.py:docstring of qiskit.circuit.quantumcircuit.QuantumCircuit.draw:30: ERROR: Unexpected indentation.
/home/vsts/work/1/s/.tox/docs/lib/python3.9/site-packages/qiskit/circuit/quantumcircuit.py:docstring of qiskit.circuit.quantumcircuit.QuantumCircuit.draw:31: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/vsts/work/1/s/.tox/docs/lib/python3.9/site-packages/qiskit/visualization/circuit/circuit_visualization.py:docstring of qiskit.visualization.circuit.circuit_visualization.circuit_drawer:30: ERROR: Unexpected indentation.
/home/vsts/work/1/s/.tox/docs/lib/python3.9/site-packages/qiskit/visualization/circuit/circuit_visualization.py:docstring of qiskit.visualization.circuit.circuit_visualization.circuit_drawer:31: WARNING: Block quote ends without a blank line; unexpected unindent.
```

They're both probably because a bullet list is starting on the first continuation line - it likely wants a blank line before (and maybe after) the start of the list in the `style` argument.

**Review by ElePT — DISMISSED** [review]
Approving in hopes that lint passes this time :)

**Review by ElePT — APPROVED** [review]
Preliminary tests passing! I'll re-approve and hope for no further surprises.

**Pull request merged**
