### PR TITLE
Corrected probabilities method names in stabilizer state for issue #11688

### LINKED ISSUE #11688: Misspelling of "probabilities" (currently "probablities") in stabilizerstate.py and test_stabilizerstate.py tests
### Environment

There are several method calls that are misspelled as "probablities" instead of "probabilities" in the 
`qiskit/quantum_info/states` and 
`test/python/quantum_info/states` classes.

methods found with misspelling:

Screenshot 2024-01-30 at 4 11 57 PM

### What is happening?

Misspelling for the word probabilities for several of the stabilizerstate.py methods and tests for stabilizerstate

### How can we reproduce the issue?

no reproduce needed
misspelling is in release Qiskit 0.45.2

### What should happen?

spelling should be corrected to align with spelling throughout project

### Any suggestions?

update the method and test names

### PR DESCRIPTION
**Pull request by DerekMiner**
### Summary
stabilizerstate and test_stabilizerstate had a misspelling of probabilities for method names in /qiskit/quantum_info/states and test/python/quantum_info/states/stabilizerstate

### Details and comments
change of the method names throughout the project to the correct spelling

fixes #11688

### CODE REVIEW

**Comment by DerekMiner** [comment]
First pull request for this project here. Regarding the branch getting out of date as other pull requests make it into main (seems to be happening a few times a day), should I be continuously rebasing the branch so its ready for review, or will the reviewer perform that when its ready?

**Comment by DerekMiner** [comment]
@jakelishman My first pull request for this project, anything else I need to do to get this pulled in?

Tests look good, a very simple change for this one

**Review by ShellyGarion — APPROVED** [review]
LGTM, thanks @DerekMiner for your first contribution to Qiskit!
You don't need to rebase or merge it into main, it will be done automatically when it will be added to the merge queue by one of qiskit-core maintainers.

**Review by alexanderivrii — APPROVED** [review]
@DerekMiner, thanks for the fix, and @ShellyGarion, thanks for the review. Since all the names are internal or tests, there is no problem to make these changes.

**Pull request merged**
