### PR TITLE
Collect classical registers using a set (#10496)

### PR DESCRIPTION
**Pull request by cjh1**
### Summary

Fixes issues with collapsing circuits with multiple conditions on the same registers.

### Details and comments

This adds a test case that adds multiple conditions on the same register. The test case is fixed by using a set to collect the classical registers in collapse_to_operation.

fixes: #10496

### CODE REVIEW

**Review by mtreinish — APPROVED** [review]
This LGTM, thanks for the fast fix.

**Comment by mtreinish** [comment]
Oh actually before I can merge this can you sign the CLA. The CLA bot comment has a link to the details on this: https://github.com/Qiskit/qiskit-terra/pull/10505#issuecomment-1652224167

**Comment by mtreinish** [comment]
Is there any update on this? We're preparing a 0.25.1 release soon and it would be great to include this fix as part of that.

**Comment by cjh1** [comment]
@mtreinish We are still waiting on IBM to respond to our email about signing the corporate CLA 😦

**Comment by 1ucian0** [comment]
hi @cjh1, Sep 29 we sent you the CCLA to sign. Let me know if you did not get it.

**Comment by cjh1** [comment]
Thanks @1ucian0, will follow up on my end.

**Comment by 1ucian0** [comment]
The Corporate CLA was signed. Our process also requieres that you sign the [CLA](https://github.com/Qiskit/qiskit/pull/10505#issuecomment-1652224167) in addition. After that, we are ready to merge.

**Comment by cjh1** [comment]
> The Corporate CLA was signed. Our process also requieres that you sign the [CLA](https://github.com/Qiskit/qiskit/pull/10505#issuecomment-1652224167) in addition. After that, we are ready to merge.

Done

**Comment by jakelishman** [comment]
No longer on hold because the CCLA is now signed :tada:

**Review by jakelishman — APPROVED** [review]
Thanks so much for working through the CCLA process.  We're streamlining our side of this as well, to help reduce friction in the future.

I've just pushed up a release note for the bugfix, but the code already looked great thanks.

**Pull request merged**
