### PR TITLE
Fix FakeProviderForBackendV2.get_backend bug

### LINKED ISSUE #8531: FakeProviderForBackendV2.get_backend raises an error when filtering by name
### Environment

- **Qiskit Terra version**: 0.21.0
- **Python version**: 3.10.4
- **Operating system**: macOS Monterey

### What is happening?

I'm getting a TypeError when trying to get a backend by name using `FakeProviderForBackendV2.get_backend`

`TypeError: 'str' object is not callable`

### How can we reproduce the issue?

Code:
```
from qiskit.providers.fake_provider import FakeProviderForBackendV2

provider = FakeProviderForBackendV2()
backend = provider.get_backend('fake_almaden_v2')
```

Output:
`TypeError: 'str' object is not callable`

### What should happen?

The provider should return the corresponding fake backend.

### Any suggestions?

_No response_

### PR DESCRIPTION
**Pull request by HuangJunye**
### Summary

Previously, `FakeProviderForBackendV2.get_backend("fake_backend_name")` raises an error due to API change in `BackendV2`. This PR fixes this bug.

Fix #8531

### Details and comments

- Fixed `get_backend` issue
- Updated fake provider module API code example to use `provider.get_backend` syntax
- Added `test_fake_provider.py`

### CODE REVIEW

**Comment by acastanedam** [comment]
Hi @HuangJunye, I am also interested in this fix. I think the test is not passing because in the assertion (line 37) the target for `insinstance` should be `FakeManilaV2`. Probably, to be more general such assertion could be written in terms of the version: `assert backend.version == 2`.

**Comment by acastanedam** [comment]
Hi, in regard to this PR, is it still feasible to include it or should one move towards the use of `BackendV2Converter` ?.
 Thansk in advance.

**Comment by HuangJunye** [comment]
> Hi, in regard to this PR, is it still feasible to include it or should one move towards the use of `BackendV2Converter` ?.
> 
>  Thansk in advance.
> 
> 

Sorry for keeping the this PR staled for so long. I think we can include it. I just need to add tests. I'll get to it next week

**Comment by acastanedam** [comment]
Hi, could I cooperate to include this MR?

**Comment by ajavadia** [comment]
@HuangJunye can you please update this branch so this bug can be fixed?

**Comment by acastanedam** [comment]
Hi, one question, will be this PR included in the current dev branch?. The problem is still there, I can volunteer to help in there as I really need the fix.
Thanks in advance

**Comment by HuangJunye** [comment]
@acastanedam I accidentally deleted the branch. I have been wanted to finish this for a year but I get distracted with other things. I apologize for the delay. Can ask for your help to finish this? You can open a new PR and copy over the changes I have made so far and add tests. That should be enough to finish it.

**Pull request closed without merging**
