### PR TITLE
Classiq drawer

### PR DESCRIPTION
**Pull request by talmic**
### Summary

Adds a circuit drawer using Classiq with `qc.draw('classiq')`

### Details and comments

Signed contribution agreement sent to qiskit@us.ibm.com‬

### CODE REVIEW

**Comment by 1ucian0** [comment]
I confirm receipt of the signed Corporate CLA. This does not replace the individual signing via cla-assistant.io.

On the code itself, depending on an external service (that requires a browser) in the core code base is a stretch. The idea is not bad at all. Too me it looks more like a format exporter than a drawer, but the discussion is almost philosophical.

Qiskit is very friendly to an extensible ecosystem and values integration with other quantum tools. I think this is a really good candidate for an external extension instead of a PR.

**Comment by talmic** [comment]
> I confirm receipt of the signed Corporate CLA. This does not replace the individual signing via cla-assistant.io.
> 
> On the code itself, depending on an external service (that requires a browser) in the core code base is a stretch. The idea is not bad at all. Too me it looks more like a format exporter than a drawer, but the discussion is almost philosophical.
> 
> Qiskit is very friendly to an extensible ecosystem and values integration with other quantum tools. I think this is a really good candidate for an external extension instead of a PR.

Hello Luciano,
No problem, I also signed the individual CLA.

Since the `draw(“tool”)` is the general way for users to show their circuits we thought that would be most convenient for them.
The browser allows for the interactive visualization experience, which is not practical from within the notebook, for large circuits it's the only efficient way to view them.
It would have a much stronger impact as part of the qiskit package, since most users would probably not install additional packages by default and so could miss this functionality.

I’d be happy to share how the circuit visualizer works for large circuits, its quite exciting :slightly_smiling_face:

**Comment by jakelishman** [comment]
I'm sorry, we're just not willing to accept the maintenance cost of a new drawer (we can barely maintain the ones we've already got), nor to include calls to external cloud APIs as part of the core Qiskit package.

What we could consider instead is to make `QuantumCircuit.draw` a plugin manager (similar to stages of the preset pass managers or `UnitarySynthesis`), such that you could release a separate package that installs itself as a plugin at the "circuit drawer" entry point, which would end up in the same user-facing API (`QuantumCircuit.draw("classiq")`), provided the user had separately installed your package.  They wouldn't have to import your package or anything, just have it installed in their environment.  That would also give you more control on keeping it updated or adding new features to the interface.

In the future, please can you open feature-request discussion issues first when proposing large new features?  I don't imagine it's much fun for you to have us say "no" to code you've written, and from our side, it doesn't feel super pleasant having to say it either, once there's already been work done, but adding a new drawer like this is just not something we can accept.

**Comment by talmic** [comment]
Hello Jake,

Thank you for your response. We understand and looking into possibilities following your suggestion.
We thought of the option of having the plugin as part of the classiq package.
If the user has the classiq package installed in his environment, then he can continue with ‘QuantumCircuit.draw(‘classiq’)’.

Could this work?

**Comment by 1ucian0** [comment]
With the plugin infrastructure that @jakelishman suggests, you will be able to do `circuit.draw("classiq")`.

**Comment by 1ucian0** [comment]
Feature requested in https://github.com/Qiskit/qiskit/issues/11900

**Comment by talmic** [comment]
Thank you for looking into it and the feedback!
I will close the PR now and we will take it inhouse to examine the plugin infrastructure.

**Pull request closed without merging**
