### PR TITLE
Fix release Pauli equivalences release note

### LINKED ISSUE #10527: Wrong global phase in 1q Pauli equivalence release note
### Environment

- **Qiskit Terra version**: 0.25
- **Python version**: n/a
- **Operating system**: n/a

### What is happening?

The release note added in #10300 contains incorrect circuit identities, and I think the actual equivalences might be wrong too (but I would have to brush up on my understanding of `global_phase` to be sure).  Specifically, the release note _should_ say $X=-iYZ$, $Y=-iZX$, and $Z=-iXY$, but these are specified incorrectly (without the minus sign).

### How can we reproduce the issue?

n/a

### What should happen?

n/a

### Any suggestions?

_No response_

### PR DESCRIPTION
**Pull request by jakelishman**
### Summary

The equivalences were all correct, just the release note had put the applied operations in the equivalence the wrong way round.

### Details and comments

Fix #10527.

I'm not _super_ certain we need to bother updating this - it's not 100% clear what our documentation strategy will be with regard to release notes when we unify the metapackage build and the Terra build.  We may keep the existing `release_notes.rst` file as something like "legacy release notes", or we may keep only the version table, and regenerate all the Terra release notes from their notes, in which case we need the Terra ones to be up-to-date.

### CODE REVIEW

**Review by garrison — APPROVED** [review]
Thank you -- the content of this looks good to me, and I (now) agree that there is only a problem with the release note, not the actual code.

The only thing I am wondering is: is `main` the proper branch on which to modify this note?  For instance, in #9545, Matt asked me to update the note on the stable branch.

Relevant reno doc section: https://docs.openstack.org/reno/latest/user/usage.html#updating-stable-branch-release-notes

**Comment by jakelishman** [comment]
I tagged this as stable backport, so it'll apply to both.  Technically it's not relevant on _any_ branch of Terra right now, because no update here will propagate through to the metapackage release-notes page, which we manually populate (`/docs/release_notes.rst`) in that repo.

The reason I targetted it to `main` here is explained (a little) in the PR message up top: with us changing our procedures, there's a fair chance that once Terra is responsible for the docs deployment, we _won't_ be using the hard-coded release notes file but instead will be regenerating the rST on demand, which means that for all versions of Terra after 0.25, they wouldn't see the correct release note unless it lands on `main`.  If that happened, then (say) Qiskit 0.45 would appear to "revert" the note back to the incorrect form, even if we fixed it in the `stable/0.44` docs.

**Comment by jakelishman** [comment]
The way our backport procedures work is effectively via cherry-pick, so in terms of reno's tracking, it should track the updates on both branches correctly with this format as well.

**Comment by 1ucian0** [comment]
@Mergifyio backport stable/0.46

**Review by 1ucian0 — APPROVED** [review]

**Pull request merged**
