### PR TITLE
Replace QuantumJob with qobj dictionary

### PR DESCRIPTION
**Pull request by ewinston**
### Summary
Replaces usage of QuantumJob with a qobj dictionary.

### CODE REVIEW

**Comment by jaygambetta** [comment]
yes quantum_job goes bye bye !!!!. On a serious side lets not delete it and delete with open_compiler once we are sure we are all happy.

**Comment by ewinston** [comment]
@jaygambetta ok I put the QuantumJob module back

**Comment by ajavadia** [comment]
@ewinston can you also update the `examples/`? There are usages of QuantumJob there, with a note that it will be removed.

**Comment by ewinston** [comment]
@ajavadia ok examples have been updated. I also reset the branch to clean up history.

**Comment by ajavadia** [comment]
It felt so good looking at all the deleted lines :)
Good to merge to me.

**Pull request merged**
