### PR TITLE
[experiment] Test out Azure GitHub branch detection for PR builds

### PR DESCRIPTION
**Pull request by Eric-Arellano**
A test for https://github.com/Qiskit/qiskit/pull/11851.

### CODE REVIEW

**Comment by jakelishman** [comment]
Fwiw, I don't automagic attempts to detect running in CI are a great idea - they're going to be very fragile to changes in the docs build process and apparently unrelated changes to CI.  I think it'd be much easier to both implement and to maintain if we (for example) set our own `QISKIT_DOCS_*` environment variables, and just organise the CI actions and `tox` to put suitable values in them.

**Comment by Eric-Arellano** [comment]
>  I don't automagic attempts to detect running in CI are a great idea

It was Matthew's suggestion as the simplest solution after we discussed alternatives  in Slack. See the (recently revised) PR description of https://github.com/Qiskit/qiskit/pull/11851 for context.

> I think it'd be much easier to both implement and to maintain if we (for example) set our own QISKIT_DOCS_* environment variables, and just organise the CI actions and tox to put suitable values in them.

What would this look like? How are you proposing we know the branch name to use in the URL for GitHub source code links? And why would this be simpler than leveraging the work GitHub Actions already does for us?

--

Either way, this experiment and conversation made me realize we can simplify https://github.com/Qiskit/qiskit/pull/11851 to not worry about Azure, since we only use Azure for PR builds. PR builds never get deployed to documentation via qiskit/documentation, so it's less critical that the URL is correct for PR docs previews against stable branches. The PR docs previews are only intended for authors to preview their docs; I'm skeptical they'll be opening up the `[source]` link to double check the line numbers are exactly correct, since that line number calculation is 100% automated.

It is critical, though, that branch builds and tag builds use the correct branch.

**Comment by jakelishman** [comment]
Oh, I understood what the aim was, and I agree that environment variables (or even `sphinx-build -D key=value` direct setters) are a good way to feed data into the docs build. I just mean that I don't think the docs build should be responsible for inferring what CI runner we're in and parsing each CI's different set of environment variables - that's something we should do in the config files for that particular CI runner.  It's just separation of concerns, and providing a better way to manually override the settings to do redeployments or the like.

For concrete examples, I mean I'd make a structure something like this.

`docs/conf.py`:

```python
git_commit = os.environ.get("QISKIT_DOCS_GIT_COMMIT", None)
if (git_ref := os.environ.get("QISKIT_DOCS_GIT_TAG", None)):
   git_ref_type = "tag"
elif (git_ref := os.environ.get("QISKIT_DOCS_GIT_BRANCH", None)):
   git_ref_type = "branch"
else:
   git_ref = None
   git_ref_type = None

# ... whatever logic you want based on that `git` information.
```

`tox.ini`:

```ini
[testenv:docs]
# ... inherit everything ...
passenv = {[testenv]passenv}, QISKIT_DOCS_*
```

`.github/workflows/docs_deploy.yml`:

```yaml
on:
  # whatever

jobs:
   docs_deploy:
       # ... whatever setup ...
       - name: Build docs
         run: tox run -e docs
         env:
             QISKIT_DOCS_GIT_COMMIT: ${{ github.sha }}
             QISKIT_DOCS_GIT_TAG: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
             QISKIT_DOCS_GIT_BRANCH: ${{ github.ref_type == 'branch' && github.ref_name || '' }}
```

`.azure/docs.yml`:

```yaml
jobs:
  - job: "Docs"
    steps:
        # ... whatever ...
        - bash: tox run -e docs
          env:
              QISKIT_DOCS_GIT_COMMIT: ${{ variables['Build.SourceVersion'] }}
              ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
                  QISKIT_DOCS_GIT_BRANCH: ${{ variables['Build.SourceBranchName'] }}
              ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
                  QISKIT_DOCS_GIT_TAG: ${{ variables['Build.SourceBranchName'] }}
```

---

I might have made a couple of syntax or variable-name mistakes in the GHA and Azure file examples, but that's the general gist of what I meant.  It keeps GitHub-specific logic in GitHub-specific config files, Azure-specific logic in Azure files, and lets the docs build be just about what it actually wants to know, so it's easier to override locally as well.

**Comment by jakelishman** [comment]
Even if you're only concerned with working on GitHub Actions, I'd still suggest a structure like that will make it easier to make manual deployments if the docs build were to fail or need to be rebuilt as a post release following a failure on a tag, or something else like that. 

We don't need a redeployment to emulate some CI runner's config, just so we can reparse it into the simple information we actually wanted.  In regular CI runs, as you say, we want to use what's available to us, which this does too.  This also means the docs build wouldn't be quite so tied to GitHub Actions, so if we needed to move it, it wouldn't be a problem.

**Comment by Eric-Arellano** [comment]
Ah, I misunderstood what you meant. My bad, Jake. Thank you for taking the time to clarify in-depth! I implemented the spirit of your suggestion at https://github.com/Qiskit/qiskit/pull/11851 - it's now ready for review.

**Pull request closed without merging**
