### PR TITLE
Add official support for Python 3.13

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit adds "official" support for Python 3.13 to Qiskit. We implicitly supported it previously because nothing in Qiskit itself was incompatible with 3.13 and we use the stable ABI from rust which is compatible with new releases. But to mark 3.13 as "official" we just need to add it to CI, including the cibuildwheel test phase, and add the trove classifier to the package metadata indicating 3.13 is supported.

### CODE REVIEW

**Comment by mtreinish** [comment]
This is currently blocked on: https://github.com/Qiskit/qiskit/issues/12655 and https://github.com/Qiskit/qiskit/issues/13305 because we need to use scipy 1.14 to get wheels with python 3.13 support.

**Review by jakelishman — COMMENTED** [review]
On a quick scan myself, looks like we also have the Python versions set in `asv.conf.json`.  Otherwise this looks fine to me.

**Comment by mtreinish** [comment]
> On a quick scan myself, looks like we also have the Python versions set in asv.conf.json. Otherwise this looks fine to me.

Added in https://github.com/Qiskit/qiskit/pull/13309/commits/fa8a8df87984253a11901ed7c18884f5737dd636

**Review by jakelishman — APPROVED** [review]

**Comment by jakelishman** [comment]
I'm fine with whatever ordering of "change the branch-protection rules" and/or "admin-merge this PR first" you want to go with.  It's not like there's a huge demand for the merge queue on a Friday evening.

**Pull request merged**
