### PR TITLE
Merge 0.45.2 contents into stable/0.46.0 branch

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This PR is a merge of the contents of the stable/0.45 branch after the 0.45.2 release. This is to ensure that the 0.46.0 release is up to date with the 0.45.x series just with the extra deprecation warnings.

### Details and comments

### CODE REVIEW

**Comment by Eric-Arellano** [comment]
We need https://github.com/Qiskit/qiskit/pull/11615 included in stable/0.46 for the docs deploy to work.

**Review by jakelishman — APPROVED** [review]
Eric: we're not on the verge of releasing 0.46 yet, this is just the intermediate merge due since 0.45.2 was released.  We'll merge up further changes from the 0.45 branch right before the release of 0.46 - there's even some suggestion/discussion that we might cut a 0.45.3 with a runtime import check that the Qiskit 0.45/1.0 environment is sound (#11617) but nothing fixed.

**Comment by jakelishman** [comment]
Oh, and the other part of the review comment: I saw that the merge was clean, so if the tests pass, there shouldn't be any worries.

**Comment by jakelishman** [comment]
For completeness' sake: I actually just learned about `git show --remerge-diff`, which is a more reliable way of investigating a merge commit, and I can see that actually the merge did have two conflicts, but they were resolved by simply taking the `stable/0.45` side, and both were minor documentation things.

**Pull request merged**
