### PR TITLE
Fix GateDirection pass

### LINKED ISSUE #10824: Unnecessary check and exception in `GateDirection` pass
### Environment

- **Qiskit Terra version**: 0.25
- **Python version**: 3.9
- **Operating system**: MacOS

### What is happening?

The `GateDirection` transpiler pass has an unnecessary check that input circuits only contain 1 register:

https://github.com/Qiskit/qiskit/blob/main/qiskit/transpiler/passes/utils/gate_direction.py#L328-L332

### How can we reproduce the issue?

```python
from qiskit.circuit import QuantumRegister, QuantumCircuit
from qiskit.transpiler import PassManager, CouplingMap
from qiskit.transpiler.passes import GateDirection

q1 = QuantumRegister(1)
q2 = QuantumRegister(1)
qc = QuantumCircuit(q1, q2)
qc.cx(1, 0)
qc.cx(0, 1)

cmap = CouplingMap([[0, 1]])
pm = PassManager([GateDirection(coupling_map=cmap)])
pm.run(qc)
```
raises 
```
TranspilerError: "GateDirection expects a single qreg input DAG,but input DAG had qregs: OrderedDict([('q67', QuantumRegister(1, 'q67')), ('q68', QuantumRegister(1, 'q68'))])."
```

### What should happen?

If the check is removed it works as you would expect:
```python

class GateDirectionFixed(GateDirection):
    
    def run(self, dag):
        layout_map = {bit: i for i, bit in enumerate(dag.qubits)}
        if self.target is None:
            return self._run_coupling_map(dag, layout_map)
        return self._run_target(dag, layout_map)

pm = PassManager([GateDirectionFixed(coupling_map=cmap)])
pm.run(qc).draw()
```
```
     ┌───┐     ┌───┐     
q77: ┤ H ├──■──┤ H ├──■──
     ├───┤┌─┴─┐├───┤┌─┴─┐
q78: ┤ H ├┤ X ├┤ H ├┤ X ├
     └───┘└───┘└───┘└───┘
```

### Any suggestions?

Remove the incorrect check for a single register from the `GateDirection.run` method

### PR DESCRIPTION
**Pull request by chriseclectic**
### Summary

Fixes #10824

### CODE REVIEW

**Review by mtreinish — DISMISSED** [review]
This LGTM, the check there was unnecessary. TBH, this is straightforward enough that it didn't need a release note or a unittest so having them is just icing on the cake.

I expect pylint might fail complaining about the `TranspilerError` in the docstring. But if it does pass I'll enqueue this for merging, otherwise it'll be easy to fix if that fails.

**Comment by jakelishman** [comment]
I don't think this is a change to be made this lightly; `GateDirection` does only make sense on physically mapped circuits, and the single `q` register _is_ (for better or worse) how Qiskit represents that.  This PR represents more than a "fix" to `GateDirection`, it represents a removal of what constitutes a "physical circuit" from Qiskit.  If anything the pass is incorrect because it doesn't enforce that there's exactly one qreg that's called `q`.

(Fwiw, I don't _like_ that method of defining physical qubits, it's just what we've got at the moment.)

**Comment by mtreinish** [comment]
I'm not actually convinced that the use of single register is a contract on the physical qubit allocation. We do that in `ApplyLayout`, but any physical circuit relies solely on `dag.find_bit(x).index` (or an equivalent) to find the physical qubit. It's the index in qubits list not the single physical register. we should use for the mapping. That being said since `ApplyLayout` works this way I'm sure there is an implicit assumption in other places, but removing the check here doesn't hurt anything because I contend it really shouldn't be a hard requirement.

**Comment by mtreinish** [comment]
Also, even if it's our API contract we don't need to eagerly raise an exception like this, it's not the job of every pass to do input validation.

**Comment by jakelishman** [comment]
> but any physical circuit relies solely on `dag.find_bit(x).index` (or an equivalent) to find the physical qubit. It's the index in qubits list not the single physical register

This isn't fully true in any of the routing passes; they typically do
```python
canonical_register = dag.qregs["q"]
initial_layout = Layout.generate_trivial_layout(canonical_register)
# and sometimes
layout_mapping = {bit: index for index, bit in enumerate(canonical_register)}
```
Sometimes they _also_ look at `dag.qubits` or use `dag.find_bit` in some cases, but they all begin by requiring a single `q` qreg, no loose qubits and all the qubits in order, so the assumption of what constitutes a physical circuit is still there.  That's not directly used here, but in general `dag.find_bit(bit).index` cannot be relied on to refer to a physical qubit index; you need to be sure that you've got a physical-mapped circuit before it's safe to make that assumption.  A single `q`-named qreg being the "proof" of that is at the least implied to be part of the API surface because of the error messages in the checking cases (e.g.) https://github.com/Qiskit/qiskit/blob/2ab1e547e71b08592245970ec4a8dff90ac8842e/qiskit/transpiler/passes/routing/utils.py#L22-L23

I agree that it's not necessarily the contract of `GateDirection` to raise an exception, but the problem that the call in the linked issue here is not a physical circuit as Qiskit "defines" it isn't gone, and so this PR would be us sanctioning a currently incorrect use of the API.

In a more strongly typed language, this wouldn't be allowed; the caller would need to produce some sort of `PhysicalCircuit` or `PhysicalQubit` instances in order to use `GateDirection` at compile-time, so it's clear in the call contract that the onus is on the user to assert that they've got physical qubits.  I'm not a fan of this PR because it's implicitly saying that _any_ circuit can now be automatically considered physical without the caller typing it as such themselves to be clear at what point _they_ began to make that assumption.  We've had enough misunderstandings and in some cases bugs between "virtual" and "physical" qubits across the library that I'm not keen to remove what little library-side enforcement of it we have without good reason or a replacement.

**Comment by jakelishman** [comment]
More to the point: is there any reason why it would be especially onerous for the calling in the linked issue just to use the "correct" form?  All that's needed is to manually make the circuit physical by changing
```python
q1 = QuantumRegister(1)
q2 = QuantumRegister(1)
qc = QuantumCircuit(q1, q2)
qc.cx(1, 0)
qc.cx(0, 1)
```
into
```python

q1 = QuantumRegister(1)
q2 = QuantumRegister(1)
qc = QuantumCircuit(QuantumRegister(name="q", bits=q1[:] + q2[:]))
qc.cx(1, 0)
qc.cx(0, 1)
```
(if the `q1` and `q2` even need to be registers in the first place)

**Comment by mtreinish** [comment]
TBH, I don't think the enforcement is enforcing anything of value, and this PR is of such little impact it's wasted effort to continue arguing over it. The thing to remember is that there is nothing stopping someone from running gate direction standalone. You could easily do:

```python
q1 = QuantumRegister(1)
q2 = QuantumRegister(1)
qc = QuantumCircuit(q1, q2)
qc.cx(1, 0)
qc.cx(0, 1)
direction_qc = GateDirection(CouplingMap.from_line(2, bidirectional=False))(qc)
```

and that is a completely valid use case from my PoV. The pass shouldn't be enforcing that it is running as part of full pipeline especially as it has a small well defined job (which maybe could be documented better). I agree the model around physical vs virtual circuits is far from ideal, and things can get mixed frequently. But that doesn't change because of this PR, nor does this PR make the situation any appreciably different, except from a philosophical standpoint. I think short of defining physical qubits and physical circuits explicitly and then making a hard contract to make the distinction clear in which domain a pass (or anything) is working in this ambiguity is something we have to live with (and have been). All this really does is increase the general utility of the pass because it makes it easier to use in custom workflows (not just the above example), without introducing any potential regression.

The only thing I would potentially ask for here to address your concerns is we can document the implicit assumption that qubit indices are the physical qubit index in either the target or coupling map. This is the implicit assumption the pass is actually working off of, so making it explicit in the documentation seems like a good step.

**Comment by jakelishman** [comment]
I don't agree that a check that the input is physical is worthless, nor that this PR is innocent in slackening what little definition of physical circuits we have, but I won't prevent it from merging (why I didn't put a "request changes" review in the first place).

I totally agree that somebody can call or use `GateDirection` outside our pipelines, and that's a large part of why I think it's important that they should have to prove that they've got a circuit that's defined on physical qubits before they're allowed to call it.

**Comment by jakelishman** [comment]
(and yeah, I'd appreciate it if it is going to merge that we do at least document the required contract that the bit indices represent the physical qubits in the coupling map)

**Comment by mtreinish** [comment]
I guess I just don't agree that our meaning of physical in the transpiler is a flat register `"q"` for all qubits in the target. I've always viewed that as more an implementation detail of just `ApplyLayout` and nothing more. I'm not surprised we have things actively checking against it (I knew sabre swap, and stochastic swap used it) but for every pass I've written that's operating on physical qubits the register is always ignored. I think we should open up a separate issue to clarify this, either via documentation or actually typing it like we've talked about forever.

**Comment by jakelishman** [comment]
Sure, that works well for me - I would for sure be keen to formalise the concept of physical qubits.

**Review by mtreinish — APPROVED** [review]
I just added a note to the docstring about the assumption on qubit indices the pass makes. This LGTM (assuming I didn't break lint or the docs build).

**Pull request merged**
