### PR TITLE
Added additional check related to SymbolicPulse disable_validation

### PR DESCRIPTION
**Pull request by arthurostrauss**
### Summary
We add here an additional check for validating parameters of the parameter_manager for the pulse level for the specific case of SymbolicPulse, which now has a class attribute disable_validation (check this PR: https://github.com/Qiskit/qiskit/pull/11029)

### Details and comments

This PR aims to bring consistency in the effort of enabling the user to choose if parameter validation should be performed. This would also constitute a first step towards enabling pulse parameter assignment within a JAX framework, to enable faster simulations of pulse schedules with Qiskit Dynamics for example.

### CODE REVIEW

**Review by TsafrirA — CHANGES_REQUESTED** [review]
Nice catch @arthurostrauss .
Could you add a test to `test/python/pulse/test_parameter_manager.py`? Set `disable_validation` to `True` and assign invalid parameters to verify that everything works correctly. You can use `patch` like was done [here](https://github.com/Qiskit/qiskit/blob/523ea748b34cc1c007eda6e9e673ab6742b304a0/test/python/pulse/test_pulse_lib.py#L628-L636).

The [release notes](https://github.com/Qiskit/qiskit/blob/main/releasenotes/notes/symbolic-pulse-disable-validation-19cd8506b3a839b6.yaml) added in #11029 should also be updated to reflect that validation will not be triggered by parameter assignment.

FYI - @nkanazawa1989

**Comment by TsafrirA** [comment]
@arthurostrauss 
The PR fails the lint test. If you get it to pass, the PR will be ready for final review. Try `tox -eblack` and `tox -elint-incr`.

**Comment by arthurostrauss** [comment]
I reformatted the files but it seems that one azure test is not passing at the moment. Any idea what it could be?

**Comment by TsafrirA** [comment]
I think it's not related to this PR. I asked @nkanazawa1989 to restart the CI test, and give a final review.

**Review by nkanazawa1989 — APPROVED** [review]
LGTM. Thanks @arthurostrauss and @TsafrirA :)

**Pull request merged**
