### PR TITLE
Remove deprecated functions, options, and behavior from circuit_drawer

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

In the 0.7 release we deprecated several functions, options, and
behaviors in the circuit drawers. Now that we've got that release out
the door we can stage the removal of those things. This commit does that
and removes all the things we deprecated to stage for removal in the
circuit drawers.

### Details and comments

### CODE REVIEW

**Comment by diego-plan9** [comment]
We tend to fully deprecate near the end of a major release (ie. in this case, when `0.8` is published), to give enough leeway to users and also taking into account that minor releases (`0.7.1`, etc) might happen in the meantime, sometimes in short spans. Do we really want to modify that convention in this particular case?

**Comment by mtreinish** [comment]
> We tend to fully deprecate near the end of a major release (ie. in this case, when `0.8` is published), to give enough leeway to users and also taking into account that minor releases (`0.7.1`, etc) might happen in the meantime, sometimes in short spans. Do we really want to modify that convention in this particular case?

That doesn't make any sense to me. If we treated master that way we'd never be able to land new features or any other potentially breaking change. If we need to do a point release for a bugfix that's why we have the stable branch right? We'll have to port the patches for a point release to that branch. Either we open master for 0.8 development or we don't. The intent with these deprecations was to always remove them post 0.7 and if we've really opened 0.8 development on master then there is no reason to wait. I'd rather not keep around code we're not supporting and clean things up sooner, especially before we make any bigger changes in the near future.

**Comment by jaygambetta** [comment]
@mtreinish and @diego-plan9 im good to start doing this now. We should only use 0.7.1 to fix bugs.

**Comment by diego-plan9** [comment]
Ok - created #1646 for keeping track.

**Comment by jaygambetta** [comment]
@mtreinish can you fix the linter errors

**Pull request merged**
