### PR TITLE
Add `Instruction.assign_parameter` to delegate correct binding to instructions themselves

### LINKED ISSUE #6674: Gate with parameterized gate *and* phase is bound incorrectly
### Information

- **Qiskit Terra version**: main @ a2cc56f82ebbfd83fb9dc87e9f5dd59eacba9709
- **Python version**: 3.7.9
- **Operating system**: macOS

### What is the current behavior?

A circuit that contains a gate with the same parameter both in a gate and the global phase does bind the parameters, but it still shows up as free in the bound circuit.

### Steps to reproduce the problem

```python
from qiskit.circuit import *

x = Parameter('x')
inner = QuantumCircuit(1)
inner.global_phase = x
inner.rx(x, 0)

bound = inner.assign_parameters([0])
print("Inner", bound.parameters, "and decomposed", bound.decompose().parameters)

outer = QuantumCircuit(inner.num_qubits)
outer.append(inner.to_gate(), outer.qubits)

bound = outer.assign_parameters([0])
print("Outer", bound.parameters, "and decomposed", bound.decompose().parameters)
```
Results in
```
Inner ParameterView([]) and decomposed ParameterView([])
Outer ParameterView([]) and decomposed ParameterView([Parameter(x)])
```

### What is the expected behavior?

The decomposed `outer` circuit should not have free parameters.

### LINKED ISSUE #7486: Bound parameters is back under certain conditions in QuantumCircuit.
### Environment

- **Qiskit Terra version**: qiskit-terra': '0.20.0'
- **Python version**: 3.8
- **Operating system**: macOS

### What is happening?

If you decompose the parameterized quantum circuit with control and inverse, the parameters will be back.

### How can we reproduce the issue?

```python
from qiskit.circuit import Parameter
from qiskit import QuantumCircuit

qc = QuantumCircuit(1)
param = Parameter("old")
qc.p(param, 0)
controlled = qc.control()
new_param = Parameter("new")
qc = QuantumCircuit(2)
qc.append(controlled.assign_parameters({param: new_param}).inverse(), qc.qubits)

print(qc)
print(qc.decompose().decompose())
```

### What should happen?

The parameters of both circuits should be `new`.

### Any suggestions?

_No response_

### PR DESCRIPTION
**Pull request by Cryoris**
### Summary

Fixes #7486 and fixes #6674.

### Details and comments

~~WIP as the PR misses reno and test.~~

### CODE REVIEW

**Review by jakelishman — COMMENTED** [review]
I think this is patching a particular symptom of a larger problem; `QuantumCircuit` shouldn't be responsible for managing the internals of classes in its data.  This approach of having special cases for `ControlledGate` will become untenable when #7087 merges, because `QuantumCircuit` won't even know what might be added to it.

I think a more robust solution is to have `Instruction` define a new method `assign_parameters` which can take a dictionary `{old_param: param}`, and delegate the modifications to those classes.  In theory, `Instruction`s with many parameters would need their own bookkeeping of where parameters are (similar to the current `ParameterTable` in `QuantumCircuit`), but in practice most instructions have at most 3 parameters, and there it'll probably be faster for them to just scan their parameters.  `QuantumCircuit` would still keep its table, so it only calls the modifying method on instructions that need it.

This may have some (hopefully minor) speed implications, but I'd think it's worth it.  I'm fairly sure there are other bugs kicking around where various `Instruction.params` updates don't propagate everywhere - basically any instruction that itself contains `Instruction` instances is liable to be broken.

**Comment by woodsp-ibm** [comment]
As I commented in the referenced issue you can see this has been seen by end users. Maybe this fix should be backported too.

**Comment by Cryoris** [comment]
> I think a more robust solution is to have Instruction define a new method assign_parameters which can take a dictionary {old_param: param}, and delegate the modifications to those classes.

Yes, I agree that's the more sustainable solution. I'll give that a shot 🙂

**Comment by jakelishman** [comment]
Could you run some benchmarks on applications which make heavy use of parameterised circuits and controlled instructions?  There might be some suitable in the metapackage's benchmark suite already, which you can run with `asv dev`.

It'd be good to know exactly what sort of performance hit we're dealing with (if at all) before reviewing everything.

**Comment by jakelishman** [comment]
Just wanted to explicitly add to this that I see this as compatible with other changes to parameter handling, but maybe not totally needed. I believe that with run-time parameters in `CircuitInstruction` (i.e. within `QuantumCircuit.data` explicitly), the initial problem this PR tried to solve (`ControlleeGate`) will automatically be fixed, but there will still be the possibility for custom `Instruction` subclasses to contain `ParameterExpression` values in their "state" fields.  The new method in this PR would still be needed/useful to support that use-case.

**Comment by Cryoris** [comment]
Closing for now as stalled.

**Pull request closed without merging**
