### PR TITLE
Add `copy` keyword argument to `QuantumCircuit.append`

### PR DESCRIPTION
**Pull request by jakelishman**
### Summary

We always copy compile-time parametric instructions during `QuantumCircuit.append` to avoid accidental mutation of other references in a call to `assign_parameters(inplace=True)`.  However, mostly our rotation gates are added through things like `QuantumCircuit.rz`, where the only reference to the `RZGate` is internal to the `QuantumCircuit`, so creating and immediately copying it is a waste of time.

This commit adds a `copy` argument to `QuantumCircuit.append`, so we can set it to `False` in places where we know we own the instruction being added.

### CODE REVIEW

**Review by ElePT — COMMENTED** [review]
I think that this is a nice addition, there are many cases where we create circuits just to append to another one and never re-use them again. According to the reno, this PR is also a bugfix. To make sure I understand it, did `append` not copy instructions with `ParameterExpressions` before this?

**Comment by jakelishman** [comment]
Yeah, exactly:
```python
from qiskit.circuit import Parameter, QuantumCircuit
from qiskit.circuit.library import RZGate

a = Parameter("a")
qc = QuantumCircuit(1)

gate = RZGate(a)
qc.append(gate, [0], [])
assert qc.data[-1].operation is not gate, "parameter"
gate = RZGate(a + 0)
qc.append(gate, [0], [])
assert qc.data[-1].operation is not gate, "expression"
```
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[50], line 13
     11 gate = RZGate(a + 0)
     12 qc.append(gate, [0], [])
---> 13 assert qc.data[-1].operation is not gate, "expression"

AssertionError: expression
```

**Comment by jakelishman** [comment]
Also yeah, the biggest improvement here is actually in the construction of _any_ parametric circuit using the convenience alias methods on `QuantumCircuit` like `.rz` - before these, those methods would copy despite having only just constructed the only reference to the gate just a line or two above, and that drop that reference again immediately.

**Review by ElePT — APPROVED** [review]
Sounds good

**Pull request merged**
