### PR TITLE
Support dynamic circuit in BackendEstimator

### PR DESCRIPTION
**Pull request by ikkoham**
### Summary

This PR makes BackendEstimator supports dynamic circuit.

### CODE REVIEW

**Comment by garrison** [comment]
It is actually not clear to me why `circuit.num_qubits == observable.num_qubits` should be relaxed to `circuit.num_qubits >= observable.num_qubits` in order to support dynamic circuits.  Can you clarify?

**Comment by ikkoham** [comment]
@garrison Thanks. The intent of this relaxed condition is to support circuits with auxiliary qubits like the test example https://github.com/Qiskit/qiskit-terra/pull/9700/files#diff-ec629567417753086ce09aba87c8dc9f34ab946d903fe809200ba692a7ed8e2dR364

**Comment by garrison** [comment]
I see.  But in that example, why not just specify the observable as `"ZI"`, i.e., such that it is over _all_ the qubits?

Otherwise, you presumably need some logic to determine what is an "auxiliary" qubit or not.  For instance, is it considered an auxiliary qubit if it contains a `Measure` instruction somewhere?  If so, what if the `Measure` is immediately followed by a `Reset`?  Would one be prevented from taking expectation values over such qubits?

Another way of phrasing my question: With this PR, you could pass the same circuit multiple times along with observables of different numbers of qubits.  How are these different observables expected to be handled within an Estimator implementation?

**Comment by ikkoham** [comment]
You are right. Certainly there is no way to distinguish if they are auxiliary qubits or not, so it may be a good idea to have the user explicitly enter I.

**Comment by t-imamichi** [comment]
I come up with an idea to make a separate classical register for measurements. Could you take a look at it, @ikkoham?
https://github.com/ikkoham/qiskit-terra/pull/78

**Comment by ikkoham** [comment]
Please release 0.25.0 if this PR blocks it.

**Comment by ikkoham** [comment]
I initially made this PR with the intention of supporting dynamic circuits, but I noticed that it is bug for circuits with classical registers, even if they are not dynamic. I hope it will be merged as soon as possible.

**Comment by t-imamichi** [comment]
OK. I review it asap

**Comment by t-imamichi** [comment]
When I ran the test locally, I found the following warning. The `denom` value gets 0. It would be better to check zero division before `expvals /= denom`.
```
./Users/ima/tasks/3_2023/qiskit/terra/qiskit/primitives/backend_estimator.py:454: RuntimeWarning: invalid value encountered in divide
  expvals /= denom
```

**Comment by t-imamichi** [comment]
How is the final measurement treated?
1. Should the final measurement order be same as the observable order?
2. What if final measurements are applied to only q0 and q2, and q1 is left not measured? Should two-qubit observables be passed with the circuit?

**Comment by t-imamichi** [comment]
minor update of tests. https://github.com/ikkoham/qiskit-terra/pull/79/

**Comment by ikkoham** [comment]
Discussing internally.

**Review by t-imamichi — APPROVED** [review]
LGTM

**Pull request merged**
