### PR TITLE
Deprecate legacy primitive attributes in base classes

### PR DESCRIPTION
**Pull request by chriseclectic**
### Summary

These attributes should have already  been deprecated when the Estimator and Sampler run signatures were changed to take circuits instead of indices.

### CODE REVIEW

**Comment by jakelishman** [comment]
I've nothing against this PR, I've just killed its tests til tomorrow to free up CI runners for the release-queue pipeline.

**Comment by t-imamichi** [comment]
It causes an infinite recursion for other primitive implementations.
E.g.,
```python
from qiskit_aer.primitives import Sampler as AerSampler
from qiskit import QuantumCircuit

qc = QuantumCircuit(2, 2)
qc.measure([0, 1], [0, 1])
sampler = AerSampler()
_ = sampler.run(qc).result()
```

output
```
Traceback (most recent call last):
  File "/Users/ima/tasks/3_2023/qiskit/terra/tmp/aer_sampler.py", line 7, in <module>
    _ = sampler.run(qc).result()
  File "/Users/ima/tasks/3_2023/qiskit/terra/qiskit/primitives/base/base_sampler.py", line 165, in run
    return self._run(
  File "/Users/ima/envs/dev310/lib/python3.10/site-packages/qiskit_aer/primitives/sampler.py", line 149, in _run
    circuit_indices.append(len(self._circuits))
  File "/Users/ima/tasks/3_2023/qiskit/terra/qiskit/primitives/base/base_sampler.py", line 120, in __getattr__
    if name in dep_defaults and not hasattr(self, name):
  File "/Users/ima/tasks/3_2023/qiskit/terra/qiskit/primitives/base/base_sampler.py", line 120, in __getattr__
    if name in dep_defaults and not hasattr(self, name):
  File "/Users/ima/tasks/3_2023/qiskit/terra/qiskit/primitives/base/base_sampler.py", line 120, in __getattr__
    if name in dep_defaults and not hasattr(self, name):
  [Previous line repeated 496 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

According to Python documentation, hasattr is realized by calling getattr. So, calling hasattr in getattr causes the infinite recursion.

> This is implemented by calling getattr(object, name) and seeing whether it raises an [AttributeError](https://docs.python.org/3/library/exceptions.html#AttributeError) or not.

https://docs.python.org/3/library/functions.html?highlight=hasattr#hasattr

It might be good to check attributes by dir(self).

**Comment by t-imamichi** [comment]
According to Python documentation, `hasattr` is realized by calling `getattr`. So, calling `hasattr` in `getattr` causes the infinite recursion.

> This is implemented by calling getattr(object, name) and seeing whether it raises an [AttributeError](https://docs.python.org/3/library/exceptions.html#AttributeError) or not.

https://docs.python.org/3/library/functions.html?highlight=hasattr#hasattr

**Comment by t-imamichi** [comment]
It is also necessary to raise appropriate AttributeError if an unknown attribute is given.

```python
from qiskit.primitives import Sampler

sampler = Sampler()
sampler.foo
```

output
```
Traceback (most recent call last):
  File "/Users/ima/tasks/3_2023/qiskit/terra/tmp/11051.py", line 4, in <module>
    sampler.foo
  File "/Users/ima/tasks/3_2023/qiskit/terra/qiskit/primitives/base/base_sampler.py", line 129, in __getattr__
    return super().__getattr__(name)
AttributeError: 'super' object has no attribute '__getattr__'. Did you mean: '__setattr__'?
```

Should be `AttributeError: 'Sampler' object has no attribute 'foo'`

**Comment by t-imamichi** [comment]
I made a PR to address the two issues above https://github.com/chriseclectic/qiskit-terra/pull/57.

**Comment by jakelishman** [comment]
The whole `hasattr`/`dir` stuff is actually skippable in general: `__getattr__` is only called if the standard attribute lookups fail (i.e. the attribute doesn't exist statically), which is the exact circumstance you're trying to catch here.  You can just ask the part about "is it one of the attributes we want to warn about?", because if you reach `__getattr__`, it already didn't exist:

```python
In [1]: class A:
   ...:     def __init__(self):
   ...:         self.a = "hello"
   ...:     def __getattr__(self, key):
   ...:         print(f"__getattr__: '{key}'")
   ...:         raise AttributeError(f"'{type(self).__name__}' object has no attribute '{key}'")
   ...:
   ...: a = A()
   ...: a.a, a.b
__getattr__ : 'b'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 9
      6         raise AttributeError(f"'{type(self).__name__}' object has no attribute '{key}'")
      8 a = A()
----> 9 a.a, a.b

Cell In[1], line 6, in A.__getattr__(self, key)
      4 def __getattr__(self, key):
      5     print(f"__getattr__     : '{key}'")
----> 6     raise AttributeError(f"'{type(self).__name__}' object has no attribute '{key}'")

AttributeError: 'A' object has no attribute 'b'
```

Note that there's no `__getattr__: 'a'` line.

(If in the future you want a magic method that's _always_ called: `__getattribute__` is called on every get, before `__getattr__` if applicable.)

**Comment by t-imamichi** [comment]
Thank you, Jake. I simplified the PR https://github.com/chriseclectic/qiskit-terra/pull/57

**Comment by chriseclectic** [comment]
Thanks for fixing that @t-imamichi

**Review by ikkoham — APPROVED** [review]
Thanks. Looks good to me.

**Pull request merged**
