### PR TITLE
Fix incorrect signage in `qDRIFT` synthesis

### PR DESCRIPTION
**Pull request by TheBabu**
### Summary
~~Add `save_signs` argument for qDRIFT synthesis so user can decide whether to preserve the signs of the original evolution operator in the qDRIFT Trotter synthesis.~~
Fix for incorrect implementation of `qDRIFT` synthesis.

### Details and comments
In the original formulation of qDRIFT (https://arxiv.org/abs/1811.08017) the coefficients of each of the terms in the Hamiltonian was assumed to be positive. The current way that `qdrift` handles this restriction is by arbitrarily taking the absolute value of each of the coefficients. However, the current implementation is wrong because it doesn't add back the original sign of those coefficients. ~~However, it is useful to preserve the signs of the original Hamiltonian, such keeping gradient directionality intact. This change will aim to allow to user to decide how to handle negative coefficients. The default behavior is consistent with the original code.~~

### CODE REVIEW

**Comment by TheBabu** [comment]
@Cryoris Is testing required for this change, if so can I just "duplicate" the previous 2 tests but with a different operator (that has negative coefficients) to simulate?

I should maybe ask first of, can I actually apply this change to Qiskit 🙃

**Comment by Cryoris** [comment]
From looking at the paper it seems that the sign should definitely be preserved, and the current behavior is actually wrong. In addition, isn't there a factor `lambda/N` missing?

**Comment by TheBabu** [comment]
I believe the factor is correct, at line 79: 
```py
# The protocol calls for the removal of the individual coefficients,
# and multiplication by a constant evolution time.
evolution_time = lambd * time / num_gates
```
This should cover it.

Also, can you reference where it says in the paper the signs should be preserved? My understanding is that the assumption is that the coefficients were assumed to be positive to begin with.

**Comment by Cryoris** [comment]
> I believe the factor is correct, at line 79:

Ah perfect 👍🏻 

> Also, can you reference where it says in the paper the signs should be preserved? My understanding is that the assumption is that the coefficients were assumed to be positive to begin with.

I was looking at the paper you linked 🙂 There the coefficients are assumed to be positive, since a negative factor would be absorbed into the Hamiltonian term $H_j$. So the sign still exist, it's just been moved, no?

**Comment by TheBabu** [comment]
Hm, I did not consider that at all but I think you might be right. 
image
It states that the Hamiltonian should be composed of the linear combination of Hermitians which are normalized, meaning the largest singular value of Hj is 1. The negative of the Pauli operators still satisfy this condition.

I'll modify the commit such that by default it will preserve the signs.

**Comment by TheBabu** [comment]
I pushed the new code, but I am confused about one thing, how was it passing these test cases:
In `test/python/opflow/test_evolution.py`:
```py
    def test_qdrift(self):
        """ QDrift test """
        op = (2 * Z ^ Z) + (3 * X ^ X) - (4 * Y ^ Y) + (.5 * Z ^ I)
        trotterization = QDrift().convert(op)
        self.assertGreater(len(trotterization.oplist), 150)
        last_coeff = None
        # Check that all types are correct and all coefficients are equals
        for op in trotterization.oplist:
            self.assertIsInstance(op, (EvolvedOp, CircuitOp))
            if isinstance(op, EvolvedOp):
                if last_coeff:
                    self.assertEqual(op.primitive.coeff, last_coeff)
                else:
                    last_coeff = op.primitive.coeff

    def test_qdrift_summed_op(self):
        """ QDrift test for SummedOp"""
        op = SummedOp([
            (2 * Z ^ Z),
            (3 * X ^ X),
            (-4 * Y ^ Y),
            (.5 * Z ^ I),
        ])
        trotterization = QDrift().convert(op)
        self.assertGreater(len(trotterization.oplist), 150)
        last_coeff = None
        # Check that all types are correct and all coefficients are equals
        for op in trotterization.oplist:
            self.assertIsInstance(op, (EvolvedOp, CircuitOp))
            if isinstance(op, EvolvedOp):
                if last_coeff:
                    self.assertEqual(op.primitive.coeff, last_coeff)
                else:
                    last_coeff = op.primitive.coeff
```

Since there are negative coefficents in the operator, shouldn't this have failed?

**Comment by TheBabu** [comment]
I just realized I was looking at an older commit for those test cases, before `opflow` was deprecated. There doesn't seem to be equivalent test cases for the quantum simulation synthesis stuff now. Does there need to be test cases for those?

**Comment by ShellyGarion** [comment]
> I just realized I was looking at an older commit for those test cases, before `opflow` was deprecated. There doesn't seem to be equivalent test cases for the quantum simulation synthesis stuff now. Does there need to be test cases for those?

I think that instead of `opflow` you can use the [`Statevector.evolve()`](https://docs.quantum.ibm.com/api/qiskit/qiskit.quantum_info.Statevector#evolve) method, see an example [here](https://github.com/Qiskit/qiskit/blob/ff2bbfede9c64f6de63ffe9052c8fea7a4bc7e8d/test/python/circuit/library/test_evolution_gate.py#L156). 
Perhaps you can add a few test cases for the signs?

**Comment by TheBabu** [comment]
I have updated the test case such that it better aligns with how qDRIFT is implemented. @Cryoris @ShellyGarion let me know if the changes are sufficient enough.

The old implementation of qDRIFT will now fail this test case, while the updated version where I add `np.sign(coeff)` will pass.

In order to get different samples I did something like [this](https://github.com/Qiskit/qiskit/pull/11321/files#diff-2eb09aaaab229ec46ba69b37a871c28c0dd86ff45dd2b4d3ea0f629e42862ffdR169):
`op, time=time, synthesis=QDrift(reps=reps, seed=self.seed + i)`
where I just keeping adding 1 to `self.seed`, is that acceptable?

Old version:
```bash
$ python3.8 -m tox -epy38 -- -n test.python.circuit.library.test_evolution_gate
...SNIP...
==============================
Failed 1 tests - output below:
==============================

test.python.circuit.library.test_evolution_gate.TestEvolutionGate.test_qdrift_evolution
---------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/home/ariq/qiskit/test/python/circuit/library/test_evolution_gate.py", line 176, in test_qdrift_evolution
    self.assertAlmostEqual(energy(exact), np.average(qdrift_energy), places=2)

      File "/usr/lib/python3.8/unittest/case.py", line 966, in assertAlmostEqual
    raise self.failureException(msg)

    AssertionError: (0.1-2.220446049250313e-16j) != (0.03834081766423314-6.291263806209221e-18j) within 2 places (0.061659182335766866 difference)
...SNIP...
```

New version:
```bash
$ python3.8 -m tox -epy38 -- -n test.python.circuit.library.test_evolution_gate
...SNIP...
======
Totals
======
Ran: 23 tests in 5.4652 sec.
 - Passed: 23
 - Skipped: 0
 - Expected Fail: 0
 - Unexpected Success: 0
 - Failed: 0
Sum of execute time for each test: 5.4506 sec.

==============
Worker Balance
==============
 - Worker 0 (23 tests) => 0:00:05.465235
.pkg: _exit> python /home/ariq/.local/lib/python3.8/site-packages/pyproject_api/_backend.py True setuptools.build_meta
  py38: OK (206.66=setup[200.24]+cmd[6.42] seconds)
  congratulations :) (206.79 seconds)
```

**Review by ShellyGarion — CHANGES_REQUESTED** [review]
@TheBabu - thank you very much for fixing the bug, and for adding proper tests.
In some tests we use `numpy.random.default_rng` for random seeds, but the current usage of the seeds looks OK to me.

My only comment I have is that I think the release notes should be a bit more elaborated.
Could you please add a brief explanation of the bug and its fix? (like the one that you wrote in the PR discussion).

**Review by ShellyGarion — APPROVED** [review]
LGTM, thanks for your contribution @TheBabu !

**Comment by TheBabu** [comment]
Bump, @Cryoris could you take a look at the new changes and approve the PR if it looks good 🙃

**Comment by ShellyGarion** [comment]
> Bump, @Cryoris could you take a look at the new changes and approve the PR if it looks good 🙃

@Cryoris took a long vacation, and asked @alexanderivrii and me to take care of your PR, @TheBabu .

**Review by ElePT — APPROVED** [review]
LGTM

**Pull request merged**
