### PR TITLE
Fix CPhaseGate parameter name mismatch in API docs

### LINKED ISSUE #11809: CPhaseGate parameter name mismatch in API docs
### URL to the relevant documentation

https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.CPhaseGate

### Select all that apply

- [X] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

Mismatch between theta as the parameter of the controlled phase-gate and $\lambda$ everywhere else on the page.

### PR DESCRIPTION
**Pull request by cameron-d28**
### Summary

fixes #11809

### CODE REVIEW

**Review by jakelishman — COMMENTED** [review]
Thanks for this!

In the same file, we seem to have the same discrepancy between the argument name and the documented symbol in `PhaseGate` - would you be able to swap that over to be consistent as well?

**Comment by cameron-d28** [comment]
yes i will check this out. i had a question about notation i asked on the [issue](https://github.com/Qiskit/qiskit/issues/11809#issuecomment-2382930556). it seems like changing the notation to theta rather than parameter to lambda is correct?

**Comment by cameron-d28** [comment]
i realized that the notation should be changed since the parameters are inferred from Controlled Gate

**Comment by cameron-d28** [comment]
@jakelishman later today or early am tomorrow. i can take a second to look for any more incorrect notation.

**Comment by cameron-d28** [comment]
should [RZ gate](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.RZGate) be updated to change lambda in notation to match phi in parameters?

**Comment by Eric-Arellano** [comment]
Thanks, Cameron! It looks like there is a merge conflict in `qiskit/circuit/library/standard_gates/u1.py`

**Comment by cameron-d28** [comment]
fixed it

**Comment by cameron-d28** [comment]
this should be in upcoming merge @Eric-Arellano @jakelishman

**Review by jakelishman — APPROVED** [review]
Sorry I missed the notification all that time ago - thanks for the changes!

**Pull request merged**
