### PR TITLE
Instmap with default values

### PR DESCRIPTION
**Pull request by nkanazawa1989**
### Summary
This PR allows the instmap to take a parametrized schedule and schedule block with default parameter values. This means one can `.get` schedule as in the previous, but also override parameter values. This feature may eventually help fine tuning of the backend calibrated pulses, without ugly hack of pulse entries.

### Details and comments

Currently:
```python
sx_sched = instmap.get("sx", (0,))
play_sx = sx_sched.instructions[0][1]
pulse_params = play_sx.pulse.parameters

# fine tuning
pulse_params["amp"] = 0.25

new_sx = Schedule()
new_sx += pulse.Play(type(play_sx.pulse)(**pulse_params), pulse.DriveChannel(0))
```

With this PR:
```python
sx_sched = instmap.get("sx", (0,), amp=0.25)
```

Note that we need to update below logic to enable above code, because currently backend calibrated schedules are added with the hard-coded parameter values. We need to create fully parametrized schedule, and add the schedule with `arguments` with default values. This will be a separate PR if needed, since we need to solve scope issue to distinguish parameters in a composite pulse schedule, i.e. CX schedule has multiple pulses.
https://github.com/Qiskit/qiskit-terra/blob/2d8fe45e811b124ac5a4f712c066ac63acc43eb8/qiskit/providers/models/pulsedefaults.py#L206-L208

### CODE REVIEW

**Comment by ewinston** [comment]
This seems like a good simplification. I wonder if it would be worth adding the modification methods to `Schedule` since they may be generally useful.  This might also make it easier to address the issue of composite pulses you mention and, for instance, allow a `get` operation such that one could do something like,
```python
sx_sched = instmap.get("sx", (0,)).set({amp: 0.25})
```

**Comment by nkanazawa1989** [comment]
Thanks Eric, that is another possible extension to the schedule. However, this needs a major refactoring of program representation. Currently in the `Schedule` the parameters become expression once a value is assigned. This means we need to separately manage parameters and values, and one possible solution is what we have done in the [`Call` instruction](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/pulse/instructions/call.py). However, this makes the logic complicated and perhaps we may want to upgrade `Parameter` rather than handling the logic in each program.

In the instmap, a program (i.e. `Schedule`) and signature (i.e. `Parameter`) are separately managed by using the inspect module. So the implementation is much easier.

**Comment by jakelishman** [comment]
This looks like it has fairly significant conflicts nowadays.  With the new pulse work in progress, should we close this PR as stale/obsolete?

**Comment by jakelishman** [comment]
Given no response, I'll close this PR as staled, but feel free to re-open if there's more to do.

**Pull request closed without merging**
