### PR TITLE
Fix dag visualization with Var wires

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit fixes the dag visualization for DAGs with classical variables. The Var type was not handled in the attribute callback functions for nodes and edges. This was causing the visualizer to fail if the dag contained these types. This fixes this by adding explicit handling for the Var types and using the name attribute of the Var object.

### Details and comments

### CODE REVIEW

**Review by jakelishman — COMMENTED** [review]
This generally looks fine, thanks for the catch.  Is there a simple regression test we can throw in for it?  Also: bugfix release note.

**Comment by mtreinish** [comment]
I'm skeptical of a test here, mostly because it's a visualization test and the only thing I can do besides asserting it doesn't fail is compare the output visualization. I'm not a big fan of image diff tests, and in this case will be very tricky for me to write because I have a newer version of graphviz installed locally and none of the existing graphviz based visualization tests pass locally.

**Comment by jakelishman** [comment]
For visualisation, I'm basically fine just asserting that it doesn't fail for the reasons you give. It would be good to make sure that the path is at least _run_ in the tests.

**Review by jakelishman — APPROVED** [review]
Thanks!

**Comment by jakelishman** [comment]
@Mergifyio backport stable/1.1 stable/1.2

**Pull request merged**
