### PR TITLE
[WIP] Improve speed of `sample_counts` from O(N) to O(1)

### LINKED ISSUE #8535: Make QuantumState.sample_counts faster, O(1) rather than O(N)
The current implementation of sampling $N$ shot "counts" from `QuantumState`  is $O(N)$. But there is a method that is $O(1)$.

EDIT: See #8618 for a more informed take on this issue.
EDIT: I didn't realize when writing this that it has already been discussed in various places in Qiskit. And even implemented (else where, not in `QuantumState`) for example  #8137

### The problem

Specifically, one should sample directly from the distribution of the number of counts for each index rather than sampling from the distribution of indices and then building a count map. The current method is $O(N)$ in both time and space (although the latter is a constraint due to Python, not the algorithm itself.) The method proposed here is $O(1)$ in both time and space.

Currently, to build a count map of `N` samples of measuring the state vector we:
1. Compute the probabilities $p(i) = |c_i|^2$ of each computational basis state from the instance of `Statevector`. (This step varies depending on the subclass of `QuantumState`.)
2. Collect `N` samples from this discrete distribution $p(i)$. This is (in essence) a list of integer indices $i$ each representing a basis state.
3. Build and return a count map. That is, a dictionary `counts` where each key is an integer index `i`, and `counts[i]` is the number of times `i` occurred in the list generated in step $2$.

### The solution

EDIT: See the next comment for a numpy builtin function that does this solution.

A similar, but simpler problem is sampling the number of heads in $N$ coin tosses. You could simulate $N$ coin tosses and count the number of heads. But it is faster to instead sample once from the binomial distribution.

For our sampling problem:
1. Obtain a sample $\tilde{k_1}$ of the R.V. $C_1 \sim B(N, p(1))$, the number of samples equal to the first index $1$, where $B(\cdot, \cdot)$ is the binomial distribution.
2. Use the fact that, in general, to sample from $\Pr(X=x \text{ and } Y=y)$, we can first obtain a sample $\tilde{x}$ from $\Pr(X=x)$ and then sample from $\Pr(Y=y | X = \tilde{x})$. In the case at hand, you sample from $\Pr(C_2 = k_2 | C_1 = \tilde{k_1})$, which is the density of $B(N-\tilde{k_1}, p(2) / (1 - p(1))$.
3. Repeat step 2 for $C_3$, and so on. More precisely, set $X = (C_1, C_2)$ and $Y=C_3$.

I didn't code this in Python. But the Julia code below can be easily translated.
```julia
julia> const pd =  [.1, .2, .4, .3]; # A probability distribution

julia> find_samps(pd, 10^12)  # N = 10^12
4-element Vector{Int64}:
 100000104386
 200000077220
 399999709325
 300000109069

julia> @btime find_samps($pd, 10^12);  #  This is like %timeit
  224.429 ns (2 allocations: 144 bytes)  # Time to run `find_samps` once.
```
Here is the code:

```julia
using Distributions: Binomial

"""
    find_samps(probs, N)

Sample from the distribution of counts obtained by drawing `N` samples from discrete
distribution `probs`.
"""
function find_samps(probs, N)
    sum(probs) ≈ 1 || error("probs is not a normalized probability distribution")
    Nrem = N   # N - Nrem is  the number of samples collected so far.
    counts = Int[] # samples of counts.
    q = one(eltype(probs)) # unnormalized probability of remaining i
    for p in @view probs[begin:end-1] # @view just avoids copying
        nsamp = rand(Binomial(Nrem, p / q))
        push!(counts, nsamp)
        Nrem -= nsamp
        q -= p
    end
    push!(counts, Nrem) # All the remaining counts go with last i with prob 1.
    return counts
end
```

### PR DESCRIPTION
**Pull request by jlapeyre**
Use `numpy.random.multinomial` with parameter N rather than actually generating N counts in `QuantumState.sample_counts`. This is an $O(1)$ method, whereas the current one is $O(N)$.

- [x] I have added the tests to cover my changes.
- [x] (NA, no API change) I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] reno release note

### Summary

Use a more efficient algorithm for `QuantumState.sample_counts`.
Fixes #8535.

### Details and comments

In #8535 a solution using `numpy.random.multinomial` was proposed. This PR implements it.

* The test has been updated. It now uses $10^7$ shots rather than $2000$, and a tolerance of $0.001$.
   Furthermore, we run the tests for 7 different seeds, rather than just one. The time to run all tests has
   decreased from $>6$ ms to $<6$ ms (one one machine.)
* In the following, I use a plain-python generator
    ```python
        return Counts(
            (labels[i], counts_array[i]) for i in range(len(counts_array)) if counts_array[i] > 0
        )
    ```
    Both `labels` and `counts_array` are numpy arrays. So it make sense to instead filter the indices and then build new arrays
    indexing into the two arrays. I latter is slower if the vector of probabilities is not too long. But, it would be probably faster for
    large arrays. I suppose optimizing for the larger arrays is best. We could do both with a length cutoff, but that addes
    complexity, and I think it's premature optimization at this point.

### CODE REVIEW

**Comment by jlapeyre** [comment]
For more guidance on how to evaluate this, the introduction of the [wikipedia page for multinomial distribution](https://en.wikipedia.org/wiki/Multinomial_distribution) says
> The Bernoulli distribution models the outcome of a single Bernoulli trial. In other words, it models whether flipping a (possibly biased) coin one time will result in either a success (obtaining a head) or failure (obtaining a tail). The binomial distribution generalizes this to the number of heads from performing n independent flips (Bernoulli trials) of the same coin. The multinomial distribution models the outcome of n experiments, where the outcome of each trial has a categorical distribution, such as rolling a k-sided die n times.

Note that distributions over basis states are "categorical distribution"s.

This is the same thing I said in #8535. But, here it is stated succinctly with the full authority of Wikipedia(!)

**Comment by jlapeyre** [comment]
Another thing: We should check other places in Qiskit (maybe Aer?) where we are effectively sampling from a multinomial distribution. For example, noise modeled by perturbing the circuit randomly with each shot could *not* be handled as in this PR.

**Comment by yaelbh** [comment]
We've had extensive discussions in the past about it in Aer, in both state vector and MPS simulators. Maybe @chriseclectic or Merav remember the conclusions. This came up also recently with the mock backends of qiskit-experiments (Itamar is the contact point).

I'll try to recall myself the discussion and find relevant issues and pull requests. For now I only remember that multinomial was not so magical, but I'll have to recall why. In the case of Aer, part of the story was that Aer is already written in C++, so the question became comparison between different algorithms, without the aspect of using numpy for speeding-up a program.

**Comment by yaelbh** [comment]
I'm sorry that I can't help much more than referring to a search of the word "multinomial" in the Aer repository... https://github.com/Qiskit/qiskit-aer/issues?q=multinomial
I doubt if it's of much help, but check out at least https://github.com/Qiskit/qiskit-aer/pull/831, which reminds me that @hhorii was very much involved in this, and is probably the first person to talk to.

Similarly, in qiskit-experiments: https://github.com/Qiskit/qiskit-experiments/issues?q=multinomial

**Comment by merav-aharoni** [comment]
Referring to @yaelbh 's comment above, there was some work in `MPS` to determine the fastest algorithm for `sample_measure`. We discussed three algorithms, two of which are specific to `MPS`, so are not relevant here. The only one relevant is `Algorithm 1` in https://github.com/Qiskit/qiskit-aer/pull/1377#issuecomment-956295543, where we create the accumulated probability vector, generate all the random numbers once, sort the random numbers, and then move up in the probability vector generating a count for every probability hit. 
Since Aer is in C++, it might be worth understanding what is done in the `numpy.random.multinomial` package, and implementing it in Aer.

**Comment by jlapeyre** [comment]
Thanks @yaelbh  and @merav-aharoni for pointing me to those issues.

After reading these, it's clear that this PR needs a bit more work.

To be clear, there are two related tasks.

* The *sample* task. Draw and return a list of $N$ samples from the categorical distribution with $n$ probabilities $\mathbf{p}=(p_1,\ldots,p_n)$.

* The *counts* task. Draw $N$ samples from $\mathbf{p}$. Then make a count map. That is, return a list $(c_1,\ldots, c_n)$ where $c_i$ is the number of samples equal to category $i$.

You can perform the counts task by actually generating $N$ samples and binning them. How best to sample depends on the problem parameters, that is $N$, $n$, etc.  Also on the computer language.

You can also perform the counts task by generating the counts directly from multinomial distribution, without drawing $N$ samples. This is what is done in `numpy.random.multinomial`. But, again, whether this is best depends on details of the task.

You can also perform the samples task by first doing the counts task using `numpy.random.multinomial` and then generating the counts in accordance with the results. That is, after generating the counts, make a list of length $N$ whose first $c_1$ elements are $1$, the next $c_2$ elements are $2$, etc. You could also randomly permute the results. I had not thought of this before reading the [the investigation](https://github.com/Qiskit/qiskit-aer/pull/831#issuecomment-662628023) that @lbishop related.  It seems that for some parameter regimes, it outperforms naive sampling.

**Comment by ikkoham** [comment]
LGTM, but my only concern is it breaks the API, that is it returns different counts even if the seed is the same.

**Comment by jlapeyre** [comment]
Thanks for looking at this @ikkoham !

> LGTM, but my only concern is it breaks the API, that is it returns different counts even if the seed is the same.

Oh, yes, this needs to be fixed.

However,  I realized after reading comments from @yaelbh and @merav-aharoni  that the method in this PR is in practice not always better. For example, if I have a vector of $10^6$ probabilities and I ask for one sample, using the previous implementation may be faster.

I am running experiments now to present probably as a issue rather than a PR. I will close this PR in favor of the other issue when it is ready.

**Comment by jlapeyre** [comment]
With the move to Rust, this is obsolete.

**Pull request closed without merging**
