### PR TITLE
Add pow as supported operation for ParameterExpression

### LINKED ISSUE #8959: Support powering Parameters
### What should we add?

At least integer powers should be supported. Floats can probably be supported too. Maybe even complex.

```python
from qiskit.circuit import Parameter

p = Parameter("x")

print(p * p)
print(p**2)
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-7ebbd444bd39> in <module>
      4 
      5 print(p * p)
----> 6 print(p**2)

TypeError: unsupported operand type(s) for ** or pow(): 'Parameter' and 'int'
```

### PR DESCRIPTION
**Pull request by grossardt**
### Summary

Adds powering for `qiskit.circuit.ParameterExpression` allowing to use `a**n`, `n**a`, `a**b`, `pow(a,b)` etc. for `ParameterExpression`s `a`, `b` and numbers `n`.

### Details and comments

Minimal change using default support of `pow` by Sympy/Symengine.
Also added `pow` to list of operators in `TestParameterExpressions` test case for unit testing.
Fixes #8959
Changelog: New Feature

### CODE REVIEW

**Comment by grossardt** [comment]
It seems that the Windows version (of Symengine I assume) introduces a small numerical error in pow that leads to some of the tests to fail. Not sure how to deal with this? Just loosen the test to only assert almost equal?

**Review by jakelishman — COMMENTED** [review]
Hmm, this is a slightly tricksy question.  On the one hand, I'm not keen to relax the tolerances of the test, because the expressions are a simple binary op, and the floating-point evaluation _should_ be bit-for-bit identical between the two cases.  On the other, complex-number powers are a mathematically tricky operation to perform, so they're not really akin to the simple `+`, `-`, `*` and `/` operations otherwise tested.

The failing test case is `pow(-1, 2.3)`, which in pure real-number arithmetic should be equal to $e^{3i\pi/10} = \cos(3\pi/10) + i\sin(3\pi/10)$.  The closest floats to those values would be `(0.5877852522924731+0.8090169943749475j)`, which notably _isn't_ the returned result from either component, so there's already a few-ULP difference in both `pow(-1, 2.3)` and the symbolic form.  That's quite to be expected, since even one of the basic simplifications I did ($2.3 - 2 = 0.3$) is not exactly true in floating-point operations due to rounding in the `[2, 4)` interval being different to the `[0.25, 0.5)` interval: `2.3 - 2 != 0.3`.  That gets even more tricky when introducing `pi`, and that the power is eventually going to be evaluated by summing power series in some form or another.

I think preferentially I'd like to keep the exact bit-for-bit equality assertion for `+`, `-`, `*` and `/`, because those _should_ be bit-for-bit equal.  For power, perhaps it would be cleaner to introduce a new test for power.  I don't mind too much if we want to make that use floating-point numbers that should produce bit-for-bit identical outputs, or if we want to relax the assertions to fuzzy matches with ~5 ULP tolerance (or whatever's appropriate).

---

The actual code and release note of this PR looks totally fine to me, thanks.

**Comment by grossardt** [comment]
@jakelishman Sounds good. I will add new tests for pow then (probably this weekend). Will opt for the fuzzy matches (mainly because the issue doesn't appear on Linux and I have no Windows environment for testing, so this seems easier).

PS: it looks like there are no tests for exp, log, sin, ...? or am I missing those?

**Comment by grossardt** [comment]
In `TestParameterExpressions` I changed `supported_operations` to a dictionary with values indicating tolerance for fuzzy comparison. This shouldn't break anything and leave the option to add more operations in the future.
I also used the opportunity to add a further test that asserts $x^y = exp(y log(x))$, hence testing both pow and exp, log methods (even though this mainly tests sympy functionality, that way exp, log get called at least once, which in my understanding they haven't - I was wrong about trigonometric functions which do have tests).
I hope the tests pass now (they did locally for me).

**Review by jakelishman — APPROVED** [review]
This looks great, thanks for the new tests!

**Pull request merged**
