### PR TITLE
Adding new arithmetic gates to toctree 

### LINKED ISSUE #13407: Add binary arithmetic gates to toctree
### Summary

The following gates are missing in the toctree, we should fix this post-1.3.0rc1: `ModularAdderGate`, `HalfAdderGate`, `FullAdderGate` and `MultiplierGate`.

### PR DESCRIPTION
**Pull request by alexanderivrii**
### Summary

Addresses #13407.

Should be backported to 1.3.

These fixes the docstrings for arithmetic gates and adds these gates to the toctree.

### CODE REVIEW

**Comment by ShellyGarion** [comment]
@alexanderivrii - thanks for preparing this PR!
I suggest to look carefully in the docs generated here, to see that no classes/functions in the circuit library were missed after all the updates done as part of #13046. I can't find here `qaoa_ansatz` from https://github.com/Qiskit/qiskit/pull/13361

**Comment by ShellyGarion** [comment]
I see that in the sections of "N-local circuits" and "Data encoding circuits" there are two different tables, one for functions and the other for BlueprintCircuits. However, in "Particular Quantum Circuits" there is a single table for functions and QuantumCircuits.
Should it be separated into two tables ?

Also: StatePreparation and Initialize are not BlueprintCircuits. Do they deserve their own section ?

**Comment by ShellyGarion** [comment]
FullAdderGate doc does not look well:
image

**Comment by alexanderivrii** [comment]
Addressing additional Shelly's comments in [a4b551c](https://github.com/Qiskit/qiskit/pull/13418/commits/a4b551cd56fa0435370b4d12ba4effd48b3ad0e3): state preparation circuit should have their own paragraph (done) and the long table on particular quantum circuits should be split into two (done).

**Review by ShellyGarion — APPROVED** [review]
LGTM, thanks @alexanderivrii

**Pull request merged**
