### PR TITLE
Add support for returning a DAGCircuit to TwoQubitBasisDecomposer

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit adds a new flag, use_dag, to the constructor for the TwoQubitBasisDecomposer. When set to True, the __call__ method will return a DAGCircuit instead of a QuantumCircuit. This is useful when the two qubit basis decomposer is called from within a transpiler context, as with the UnitarySynthesis pass, to avoid an extra conversion step.

### Details and comments

### CODE REVIEW

**Comment by levbishop** [comment]
Instead of adding instance state modifying the behavior of `__call__` why not just add a new member function to generate the dag? (Or maybe a member function to append to an existing dag might integrate better?)

**Comment by mtreinish** [comment]
The reason I did it this way was because in `UnitarySynthesis` there were multiple types of decomposers and not all of them support returning a `DAGCircuit`. So making it stateful like this made it easier as I just had to check the return type and not disambiguate on the decomposer's type before calling the object. That being said, I think you're right it would be better to just expand the scope here and add a matching flag to `XXDecomposer` too (and probably `qs_decomposition` in a separate PR, because it'd be the only `QuantumCircuit` returned after that).

**Comment by mtreinish** [comment]
I ran some quick asv benchmarks with this which yielded:

```
       before           after         ratio
     [b9ee7589]       [b65a3ff4]
     <main>       <dag-2q-synth>
-         123±3ms        106±0.5ms     0.86  transpiler_levels.TranspilerLevelBenchmarks.time_schedule_qv_14_x_14(0)
-         100±1ms         85.7±2ms     0.85  transpiler_levels.TranspilerLevelBenchmarks.time_transpile_qv_14_x_14(0)
-       103±0.4ms       85.9±0.5ms     0.83  transpiler_levels.TranspilerLevelBenchmarks.time_schedule_qv_14_x_14(1)
-         403±1ms          319±2ms     0.79  transpiler_levels.TranspilerLevelBenchmarks.time_quantum_volume_transpile_50_x_20(1)
-      85.1±0.4ms       66.7±0.6ms     0.78  transpiler_levels.TranspilerLevelBenchmarks.time_transpile_qv_14_x_14(1)

Benchmarks that have stayed the same:

       before           after         ratio
     [b9ee7589]       [b65a3ff4]
     <main>       <dag-2q-synth>
       52.2±0.2ms       52.7±0.2ms     1.01  transpiler_levels.TranspilerLevelBenchmarks.time_transpile_from_large_qasm(0)
        131±0.3ms        131±0.5ms     1.00  transpiler_levels.TranspilerLevelBenchmarks.time_transpile_from_large_qasm_backend_with_prop(3)
          117±2ms        117±0.8ms     1.00  transpiler_levels.TranspilerLevelBenchmarks.time_transpile_from_large_qasm_backend_with_prop(1)
             2565             2565     1.00  transpiler_levels.TranspilerLevelBenchmarks.track_depth_quantum_volume_transpile_50_x_20(0)
             1403             1403     1.00  transpiler_levels.TranspilerLevelBenchmarks.track_depth_quantum_volume_transpile_50_x_20(1)
             1403             1403     1.00  transpiler_levels.TranspilerLevelBenchmarks.track_depth_quantum_volume_transpile_50_x_20(2)
             1296             1296     1.00  transpiler_levels.TranspilerLevelBenchmarks.track_depth_quantum_volume_transpile_50_x_20(3)
             2705             2705     1.00  transpiler_levels.TranspilerLevelBenchmarks.track_depth_transpile_from_large_qasm(0)
             2005             2005     1.00  transpiler_levels.TranspilerLevelBenchmarks.track_depth_transpile_from_large_qasm(1)
             2005             2005     1.00  transpiler_levels.TranspilerLevelBenchmarks.track_depth_transpile_from_large_qasm(2)
                7                7     1.00  transpiler_levels.TranspilerLevelBenchmarks.track_depth_transpile_from_large_qasm(3)
             2705             2705     1.00  transpiler_levels.TranspilerLevelBenchmarks.track_depth_transpile_from_large_qasm_backend_with_prop(0)
             2005             2005     1.00  transpiler_levels.TranspilerLevelBenchmarks.track_depth_transpile_from_large_qasm_backend_with_prop(1)
             2005             2005     1.00  transpiler_levels.TranspilerLevelBenchmarks.track_depth_transpile_from_large_qasm_backend_with_prop(2)
                7                7     1.00  transpiler_levels.TranspilerLevelBenchmarks.track_depth_transpile_from_large_qasm_backend_with_prop(3)
              323              323     1.00  transpiler_levels.TranspilerLevelBenchmarks.track_depth_transpile_qv_14_x_14(0)
              336              336     1.00  transpiler_levels.TranspilerLevelBenchmarks.track_depth_transpile_qv_14_x_14(1)
              336              336     1.00  transpiler_levels.TranspilerLevelBenchmarks.track_depth_transpile_qv_14_x_14(2)
              272              272     1.00  transpiler_levels.TranspilerLevelBenchmarks.track_depth_transpile_qv_14_x_14(3)
        237±0.7ms        236±0.6ms     1.00  transpiler_levels.TranspilerLevelBenchmarks.time_transpile_from_large_qasm_backend_with_prop(2)
          235±1ms        235±0.5ms     1.00  transpiler_levels.TranspilerLevelBenchmarks.time_transpile_from_large_qasm(2)
        114±0.5ms          114±2ms     1.00  transpiler_levels.TranspilerLevelBenchmarks.time_transpile_from_large_qasm(1)
       54.3±0.3ms       54.0±0.5ms     0.99  transpiler_levels.TranspilerLevelBenchmarks.time_transpile_from_large_qasm_backend_with_prop(0)
          130±1ms        129±0.7ms     0.99  transpiler_levels.TranspilerLevelBenchmarks.time_transpile_from_large_qasm(3)
          1.53±0s       1.43±0.01s     0.94  transpiler_levels.TranspilerLevelBenchmarks.time_quantum_volume_transpile_50_x_20(2)
       1.88±0.01s       1.76±0.01s     0.94  transpiler_levels.TranspilerLevelBenchmarks.time_quantum_volume_transpile_50_x_20(3)
        295±0.8ms          275±5ms     0.93  transpiler_levels.TranspilerLevelBenchmarks.time_transpile_qv_14_x_14(3)
        263±0.6ms          245±1ms     0.93  transpiler_levels.TranspilerLevelBenchmarks.time_transpile_qv_14_x_14(2)
          972±3ms          889±5ms     0.91  transpiler_levels.TranspilerLevelBenchmarks.time_quantum_volume_transpile_50_x_20(0)

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
PERFORMANCE INCREASED.
```

**Review by ElePT — APPROVED** [review]
LGTM, I just have one question/curiosity. The PR description mentions that `use_dag` was added to the class construction but in practice it's been added to the `__call__` method. Was this an oversight writing the description? I think it makes more sense in `__call__` anyways, I was just curious.

**Comment by mtreinish** [comment]
I changed it after review comments from @levbishop, this commit made the change: https://github.com/Qiskit/qiskit/pull/12109/commits/3096f3850a83aba743635a4fcb1622e2a8a03abc

**Pull request merged**
