### PR TITLE
Cast fully bound `ParameterExpression` to float within the `PauliEvolutionGate`

### LINKED ISSUE #7507: ``qiskit.synthesis.MatrixExponential`` breaks if evolution time is a bound ``Parameter``
### Environment

- **Qiskit Terra version**: 0.19.0
- **Python version**: 3.7.9
- **Operating system**: mac OS

### What is happening?

Using the `PauliEvolutionGate` with a parameterized time and the `MatrixExponential` as synthesis method breaks. The reason is that the evolution time, after being bound, is not cast to a float but remains a `ParameterExpression` with 0 free parameters. That type is incompatible with SciPy which is used to compute the matrix exponential. 

### How can we reproduce the issue?

```python
from qiskit.circuit import QuantumCircuit, Parameter
from qiskit.circuit.library import PauliEvolutionGate
from qiskit.synthesis import SuzukiTrotter, MatrixExponential
from qiskit.opflow import I, X, Y, Z
from qiskit.quantum_info import Operator

# evolution time and operator we evolve
time = Parameter("t")
op = (I ^ X ^ Y) + (I ^ Y ^ X) - (Z ^ Z ^ I)

# evolution gate
synth = MatrixExponential()
evo = PauliEvolutionGate(op, time=time, synthesis=synth)

# plug into circuit
circuit = QuantumCircuit(op.num_qubits)
circuit.append(evo, range(op.num_qubits))
print(circuit.draw())

# bind time to some value and obtain matrix
value = 0.23
bound = circuit.bind_parameters([value])  # or {time: value}

print(bound.decompose())
```
produces
```
Traceback (most recent call last):
  File "/Users/jul/Qiskit/qiskit-terra/qiskit/circuit/parameterexpression.py", line 444, in __float__
    return float(self._symbol_expr)
  File "symengine_wrapper.pyx", line 1143, in symengine.lib.symengine_wrapper.Basic.__float__
  File "symengine_wrapper.pyx", line 968, in symengine.lib.symengine_wrapper.Basic.n
  File "symengine_wrapper.pyx", line 4278, in symengine.lib.symengine_wrapper.evalf
RuntimeError: Not Implemented

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "evoop.py", line 24, in <module>
    print(bound.decompose())
  File "/Users/jul/Qiskit/qiskit-terra/qiskit/circuit/quantumcircuit.py", line 1528, in decompose
    decomposed_dag = pass_.run(circuit_to_dag(self))
  File "/Users/jul/Qiskit/qiskit-terra/qiskit/transpiler/passes/basis/decompose.py", line 90, in run
    if node.op.definition is None:
  File "/Users/jul/Qiskit/qiskit-terra/qiskit/circuit/instruction.py", line 232, in definition
    self._define()
  File "/Users/jul/Qiskit/qiskit-terra/qiskit/circuit/library/pauli_evolution.py", line 105, in _define
    self.definition = self.synthesis.synthesize(self)
  File "/Users/jul/Qiskit/qiskit-terra/qiskit/synthesis/evolution/matrix_synthesis.py", line 43, in synthesize
    exp = expm(-1j * time * matrix)
  File "/Users/jul/opt/miniconda3/envs/py37/lib/python3.7/site-packages/scipy/linalg/matfuncs.py", line 255, in expm
    return scipy.sparse.linalg.expm(A)
  File "/Users/jul/opt/miniconda3/envs/py37/lib/python3.7/site-packages/scipy/sparse/linalg/matfuncs.py", line 591, in expm
    return _expm(A, use_exact_onenorm='auto')
  File "/Users/jul/opt/miniconda3/envs/py37/lib/python3.7/site-packages/scipy/sparse/linalg/matfuncs.py", line 626, in _expm
    A = A.astype(float)
  File "/Users/jul/Qiskit/qiskit-terra/qiskit/circuit/parameterexpression.py", line 450, in __float__
    ) from exc
TypeError: ParameterExpression with unbound parameters (set()) cannot be cast to a float.
```

### What should happen?

Properly evolve.

### Any suggestions?

See #7508

### PR DESCRIPTION
**Pull request by Cryoris**
### Summary

Fixes #7507.

### Details and comments

The underlying issue here is that `ParameterExpression`s, after being fully bound, often remain `ParameterExpression`s instead of being cast to float/complex. This PR fixes it very high-level, but maybe we should put this fix already at the level of `Instruction.validate_parameter`. 

Misses:
- [x] reno
- [x] test

### CODE REVIEW

**Review by kdk — COMMENTED** [review]
Is there a case where we would expect the `ParameterExpression` to not be able to be cast to a `float` while having an empty `parameters`? The error message `TypeError: ParameterExpression with unbound parameters (set()) cannot be cast to a float.` makes me wonder if something is going wrong earlier in the process.

**Comment by jakelishman** [comment]
@kdk: yes, if the parameter is complex.  From attaching pdb to the traceback, the issue here is that somewhere in the process, the time is getting turned into `0 + 0.23*I`, which can't be cast to float.  You can see that Scipy actually does try to cast the whole array to float first, and it calls the correct methods in `ParameterExpression`, which should work:
```python
In [10]: from qiskit.circuit import Parameter
    ...: import numpy as np
    ...:
    ...: t = Parameter("t")
    ...: t.bind({t: 0.25}), np.array([t.bind({t: 0.25})], dtype=float)
Out[10]: (ParameterExpression(0.25), array([0.25]))
```

**Comment by Cryoris** [comment]
Thanks for tracking that down! Another solution would be to leave `validate_parameters` as is and instead ensure that the `time` is a `float` inside the matrix synthesis. That would have the advantage that we can raise a specific error message so I changed it. But I'm also happy to revert if you think it should remain in `validate_parameters`.

**Comment by jakelishman** [comment]
Using the regression test added in this PR, but modified for Qiskit 1.0:
```python
from qiskit.circuit import Parameter, QuantumCircuit
from qiskit.quantum_info import Pauli, Operator
from qiskit.circuit.library import PauliEvolutionGate
from qiskit.synthesis import MatrixExponential

op = Pauli("X")
time = Parameter("t")
evo_gate = PauliEvolutionGate(op, time, synthesis=MatrixExponential())
circuit = QuantumCircuit(1)
circuit.append(evo_gate, [0])
bound = circuit.assign_parameters({time: 0.12})

ref = QuantumCircuit(1)
ref.rx(0.24, 0)

assert Operator(bound).equiv(ref)
```
this no longer fails, and #7507 is no longer reproducible either, so I'll close this as obsoleted.  Feel free to reopen if there's more to be done.

**Pull request closed without merging**
