### PR TITLE
added documentation for get_standard_gate_name_mapping()

### LINKED ISSUE #13108: Document `get_standard_gate_name_mapping`
`get_standard_gate_name_mapping` is referenced in the `Target` documentation now and used in several other projects (GitHub search brings up qiskit-experiments, qiskit-aer, blackwater, and qiskit-ibm-runtime among others). It would be nice to document it so it is officially part of the public API.

### PR DESCRIPTION
**Pull request by Shivansh20128**
### Summary
Added documentation for the function get_standard_gate_name_mapping() in the Standard Gates section [here](https://docs.quantum.ibm.com/api/qiskit/circuit_library#standard-gates). 

This fixes this open issue [link](https://github.com/Qiskit/qiskit/issues/13108).

### Details and comments
I have added necessary details about the function with code examples in the documentatio.

### CODE REVIEW

**Comment by Shivansh20128** [comment]
@jakelishman Please review this pull request and let me know if its alright.
Thank you

**Comment by Shivansh20128** [comment]
closes #12431 
This PR can also close [this](https://github.com/Qiskit/qiskit/issues/12431) issue. I am facing some problems contributing more as this PR has not been merged yet. And so I cannot delete my forked repo.
Please review this.
Thank You

**Comment by wshanks** [comment]
@Shivansh20128 You can use branches to have more than pull request at a time. Maybe this document helps to explain branches:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches

It is best to keep individual pull requests small and focused on one thing (like how you had this PR just adding documentation for `get_standard_gate_name_mapping` but now it has some other things). It is probably still small enough to get reviewed and merged in one pull request, but I want to leave that job to someone else :slightly_smiling_face: 

Also, I would consider adding a release note to advertise that `get_standard_gate_name_mapping` is a public function.

**Comment by Shivansh20128** [comment]
@wshanks Thank you so much for the information. I am still in the learning phase and guess it'll take some time getting used to. 

Maybe I should just remove this PR and make a new one from the beginning which contains only the required changes here (if the reviewers agree).

**Comment by Shivansh20128** [comment]
Sorry for all this mess. I am creating a new and clean PR for this issue that can be reviewed easily.
Thank you

**Comment by wshanks** [comment]
@Shivansh20128 No problem -- nice to keep things clean. You can always rewrite the history of your branch if you want to without opening a new pull request. That is not a good idea for a main branch but for a temporary one for a pull request it is okay. You can't remove comments on the PR though, so sometimes opening a new PR is nice to keep it clean.

**Pull request closed without merging**
