### PR TITLE
Fixing monitor tools

### LINKED ISSUE #7865: job_monitor fails for qiskit runtime jobs
### Informations

- **Qiskit version**: 0.35.0
- **Python version**: 3.8
- **Operating system**: Ubuntu

### What is the current behavior?
When attempting to monitor jobs that use the qiskit runtime the following error occurrs:
```
Job Status: job is queued
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_9699/736061496.py in <module>
     19 )
     20 
---> 21 job_monitor(reset_job)

~/.local/lib/python3.8/site-packages/qiskit/tools/monitor/job_monitor.py in job_monitor(job, interval, quiet, output, line_discipline)
     87         _interval_set = True
     88 
---> 89     _text_checker(
     90         job, interval, _interval_set, quiet=quiet, output=output, line_discipline=line_discipline
     91     )

~/.local/lib/python3.8/site-packages/qiskit/tools/monitor/job_monitor.py in _text_checker(job, interval, _interval_set, quiet, output, line_discipline)
     47 
     48         if status.name == "QUEUED":
---> 49             msg += " (%s)" % job.queue_position()
     50             if job.queue_position() is None:
     51                 interval = 2

AttributeError: 'RuntimeJob' object has no attribute 'queue_position'
```

### Steps to reproduce the problem
Submit a qiskit runtime job to a full queue, then monitor the job with `job_monitor(job)`

### What is the expected behavior?
The job_monitor should not exit with an exception

### Suggested solutions
Remove the assumption that the job object has a `queue_position` method, as that is not part of the base class.

### PR DESCRIPTION
**Pull request by 1ucian0**
The tools in `qiskit.tools.monitor` are a bit neglected. This PR is trying to bring them up to speed.

### `qiskit.tools.monitor.job_monitor`

Closes #7865

`job_monitor` now works with `RuntimeJob`. `JobV1` does not provide `queue_position` so a general `job_monitor` should not assume it (probably was only a thing with `IBMJob`. If `job_monitor` stays in Qiskit, it should be generic.

### `qiskit.tools.monitor.backend_monitor`

 It was not working at all, so now it works. In the future, it should work with any `BackendV2` or be moved to `qiskit-ibm-runtime` otherwise.

```python
from qiskit_ibm_provider import IBMProvider
from qiskit.tools.monitor import backend_monitor
provider = IBMProvider()
backend_monitor(provider.get_backend('ibm_sherbrooke'))
```
```
ibm_sherbrooke
==============
Configuration
-------------
    n_qubits: 127
    operational: True
    status_msg: active
    pending_jobs: 139
    backend_version: 1.4.28
    basis_gates: ['ecr', 'id', 'rz', 'sx', 'x']
    local: False
    simulator: False
    backend_name: ibm_sherbrooke
    qubit_channel_mapping: [['d0', 'm0'
....
```

### `qiskit.tools.monitor.backend_overview`

Similarly to `qiskit.tools.monitor.backend_monitor`, it was not working at all, so now it works. In the future, it should take a `BackendV2` or be moved to `qiskit-ibm-runtime` otherwise.

```python
from qiskit.tools.monitor import backend_overview
backend_overview()
```

~TODO:~
 * ~if we keep them, a bugfix reno.~ [we keep it in the `0.*` major](https://github.com/Qiskit/qiskit/pull/11414#issuecomment-1884642536)
 * ~if we dont keep them, deprecate/remove them~

### CODE REVIEW

**Comment by jakelishman** [comment]
Copying in some discussion from offline:

imo these functions aren't suitable for core Qiskit; information about queue positions and reading custom downstream fields from a `Job` subclass shouldn't be part of the core library, since it's not part of the `Job` interface.  I think we ought to be moving this functionality to the relevant packages, where it can be maintained and update as the custom `Job` subclasses changes, or as the structure of the custom information about queue position changes.

**Comment by ElePT** [comment]
I agree with @jakelishman, moving this functionality out of qiskit would also be coherent with the changes laid out in #10266 (the fake backend epic).

**Comment by 1ucian0** [comment]
It makes total sense what you are both saying.

I changed the base to `stable/0.46` and I will add the deprecation warnings.

**Comment by jakelishman** [comment]
Best check overlap with some of Matt's recent PRs - #11513 and #11514 might cover these deprecations.

**Comment by 1ucian0** [comment]
I'm merging the `mtreinish:deprecate-tools` into this one. So blocked by https://github.com/Qiskit/qiskit/pull/11514 (tagging `on hold`).

**Comment by jakelishman** [comment]
#11514 is merged now, removing hold.

**Comment by mtreinish** [comment]
Given the timeframe for the 0.46.0 release I've deferred this to 0.46.1, it's a valid bugfix for a patch release too.

**Review by kevinhartman — APPROVED** [review]
Looks good to me. The changes seem low risk given that the module they address does not currently work.

**Pull request merged**
