### PR TITLE
Consistent gate order in visualizations

### PR DESCRIPTION
**Pull request by maddy-tod**
### Summary
Fix of #1685 

Changing `topological_sort()` to `lexicographical_topological_sort()` in the DAGCircuit has ensured that generated circuits look the same in both Python 3.5 and 3.6 . This also updates output circuit so that it respects the order the user created the circuit, ie gates will appear in the output in the order that they were added to the circuit. Tests have been updated to reflect this change.

### Details and comments
WIP as failing a transpiler test for over optimization.

### CODE REVIEW

**Comment by ajavadia** [comment]
Thanks @maddy-tod, this looks good. I think the test failure might be due to this bug in the StochasticSwap pass: https://github.com/Qiskit/qiskit-terra/issues/1573

So let's keep this PR open and see if fixing that bug solves the issue. But the visualizer outputs look much better with your work.

**Comment by maddy-tod** [comment]
I have had a look into this. I think the issue comes from the fact that `dag.serial_layers()` now returns the nodes in a different order and this is used in a method of [StochasticSwap](https://github.com/Qiskit/qiskit-terra/blob/930990230c97ebdecffc6d859c28afd4585a0fb5/qiskit/transpiler/passes/mapping/stochastic_swap.py#L436). This causes the layers to be created in a different order, and as the layout of the layers created affects subsequent layers, the wrong output is generated. I'm not sure how to get around this other than perhaps adding a parameter to `node_nums_in_topological_order()` to say if the lexicographical sort is wanted, or making it a separate method which the visualizers can use.

**Comment by ajavadia** [comment]
I think we just change the ground truth for that test. The mapper is still functionally correct, it just produces a different result because it consumes a different set of layers.
As long as the circuit is correctly mapped and equivalent to the original one, the test should not fail.

**Comment by ajavadia** [comment]
I just made this update. Please take a look and let me know if you're happy with it, then we can merge.

**Comment by maddy-tod** [comment]
This looks good, thanks!

**Comment by ajavadia** [comment]
Thanks!

**Pull request merged**
