### PR TITLE
[WIP] Arithmetic circuit library subtractors

### PR DESCRIPTION
**Pull request by ManjulaGandhi**
### Summary
Implementing Twos Complement Subtractor

### Details and comments
Tests are still missing

### CODE REVIEW

**Comment by jakelishman** [comment]
@Cryoris: I don't know the purpose of the classical arithmetic parts of the circuit library, but I think you might know the history.  This PR is old and never saw review, but is from around the time of some other modifications to the arithmetic library (esp #6470) - please could you judge if it's something useful that we should include, or close the PR if not?

**Comment by Cryoris** [comment]
Yeah this would be useful to have to complete the operations in the arithmetic circuit library 🙂 

@ManjulaGandhi would you still be interested in pursuing this? Otherwise we can also close it and see if we can pick it up in the future 🙂

**Comment by ManjulaGandhi** [comment]
@Cryoris yes interested to complete this task.

**Comment by jakelishman** [comment]
I'm going to close this PR now due to lack of activity, but if @Cryoris and @ManjulaGandhi are committed to getting this actually merged, please feel free to re-open it.

**Pull request closed without merging**
