### PR TITLE
Migrate `transpiler/synthesis`

### LINKED ISSUE #10819: Deprecate qiskit/transpiler/graysynth.py
### What should we add?

Continue the work in https://github.com/Qiskit/qiskit/pull/9795 and deprecate[ `qiskit/transpiler/graysynth.py`](https://github.com/Qiskit/qiskit/blob/main/qiskit/transpiler/synthesis/graysynth.py).
The code now exists in the [synthesis library](https://qiskit.org/documentation/apidoc/synthesis.html):

- `cnot_synth` is replaced by `synth_cnot_count_full_pmh`
- `graysynth` is replaced by `synth_cnot_phase_aam`

One should follow [Qiskit deprecation policy guidelines](https://qiskit.org/documentation/deprecation_policy.html).

### PR DESCRIPTION
**Pull request by prakharb10**
### Summary
Closes #10819
Partially adresses #9667

### Details and comments
I'm unable to build the docs locally so please let me know if any doc changes are required.

I have just copied the `aqc` directory and updated references. Is it okay that the code exists in two places right now or should the (soon-to-be) deprecated methods call the new methods internally?

Will add reno once changes are approved

### CODE REVIEW

**Comment by ShellyGarion** [comment]
Hi @prakharb10 - Thank you very much for your contribution!

As for the docs, you can also see them in the build artifact here:
https://dev.azure.com/qiskit-ci/qiskit/_build/results?buildId=50719&view=results

Indeed, it's not enough to copy the `aqc` directory, you should remove the internal code and call the new methods internally. 
See for example this PR: https://github.com/Qiskit/qiskit/pull/10725

**Comment by ShellyGarion** [comment]
Hi @prakharb10 - are you still working on this PR?

**Comment by prakharb10** [comment]
Hi @ShellyGarion. I'm planning on completing this PR. I looked at the reference PR, but I had some questions. Posting here too
https://qiskit.slack.com/archives/C024ELK40TW/p1698781477136239

**Comment by ShellyGarion** [comment]
Another comment about the docs. If you want them to show up you need to update the `__init__` file in `qiskit.synthesis`.

For example, please add this line:
`.. autofunction:: synth_cnot_phase_aam`
here:
https://github.com/Qiskit/qiskit/blob/2935f0dd3a5d24843cd29dd1102157a7af1a1afe/qiskit/synthesis/__init__.py#L46

**Comment by ShellyGarion** [comment]
Hi @prakharb10 - any progress with this PR?

**Comment by ShellyGarion** [comment]
Hi @prakharb10 - since there is no progress with this PR, and since we have a strict deadline for deprecations for Qiskit 1.0 release, I will have a close your PR and start another PR soon.

**Comment by prakharb10** [comment]
Hi @ShellyGarion 
I'm sorry for not getting back to you sooner; I have been busy with school.
I understand. That sounds good.

**Comment by ShellyGarion** [comment]
Thank you @prakharb10 for your work, it is very much appreceated. I opened a new PR #11426 and added you as a co-author.

**Pull request closed without merging**
