### PR TITLE
Deprecate the discrete pulse library (#11110)

### PR DESCRIPTION
**Pull request by shindodkar**
* Promote to deprecation and correct tests

* remove `guassian` from tutorial

* Release notes

* change to 0.46.0

* Test fix

* Lynt

### CODE REVIEW

**Comment by shindodkar** [comment]
Fixed #11146

**Comment by shindodkar** [comment]
waiting for merge request if their is no change to make

**Comment by Raghav-Bell** [comment]
@shindodkar Thanks for the contribution but #11213 is a complete PR for the issue #11146. Maintainers should close or make it draft PR as it is  incomplete.

**Comment by ElePT** [comment]
As @Raghav-Bell mentioned, this issue has already been fixed by https://github.com/Qiskit/qiskit/pull/11213. Thanks for giving this issue a try but I will close the PR now.

**Pull request closed without merging**
