### PR TITLE
Enable no-value-for-parameters (pylint)

### PR DESCRIPTION
**Pull request by ikkoham**
### Summary

Related to #9614

### CODE REVIEW

**Review by jakelishman — COMMENTED** [review]
I might actually be tempted to put line-level suppressions on each of these in order to remove the option from `.pylintrc` (which I definitely agree we should do), because these lines look like a pylint bug to me.  `__new__` is a special-cased `staticmethod`, not a `classmethod` like Pylint is suggesting it is, and it should be valid to use `self` or `super()` to access it.

**Comment by jakelishman** [comment]
I actually went over to Pylint to file this, to discover that Ikko had already done so: PyCQA/pylint#8325.

**Comment by ikkoham** [comment]
@jakelishman Yes, I am sorry for the delay. After making this PR, I was thinking about the specs and started to suspect a bug, sorry to have to go through this twice. Sorry to make you take the time to look into it.

**Comment by jakelishman** [comment]
No need to apologise!  I'm totally on board with wanting this check back, and it's fun that we've found another pylint bug from Terra.

**Comment by ikkoham** [comment]
Close since it's not a priority.

**Pull request closed without merging**
