### PR TITLE
default `package_name='qiskit'` for `deprecate_func` and `deprecate_args`

### PR DESCRIPTION
**Pull request by 1ucian0**
### Summary

The decorators `deprecate_func` and `deprecate_func` take the optional parameter `package_name` which defaults to `qiskit-terra`. With  qiskit==qiskit-terra in 1.0, the default parameter is now `"qiskit"`. However, the deprecations already set, before 0.45, they need to continue using `"qiskit-terra"`.

### Details and comments

The interesting part is in `qiskit/utils/deprecation.py`. The rest is setting `package_name` to `"qiskit-terra"`.

### CODE REVIEW

**Comment by jakelishman** [comment]
Ought we to do this, or would it be better to replace all the versions with the corresponding version of the metapackage to that Terra release?  It's a real question - I don't know which way round would be more useful to users.

**Comment by 1ucian0** [comment]
> Ought we to do this, or would it be better to replace all the versions with the corresponding version of the metapackage to that Terra release? 

I dont think it makes much difference. I took this direction because implies no change in the doc (and maybe avoiding the confusion that change might generate?). Not a hill I'm willing to die on.

**Review by ElePT — COMMENTED** [review]
As a user who has been keeping track of important changes in recent versions, I remember events in "terra version basis" and could not say from the top of my head what metapackage version they correspond to, so I would prefer to keep the warnings as they are. Plus, this way it's easier to go back and check release notes or code from past terra releases.

**Comment by jakelishman** [comment]
> As a user who has been keeping track of important changes in recent versions, I remember events in "terra version basis" and could not say from the top of my head what metapackage version they correspond to

I'm the same for sure, but I'm thinking that most people probably are less so, and moving forwards to the 1.0 era, it's going to be easier to find documentation and information from Qiskit version numbers than Terra ones.  That said, I think the hope is that there's no active deprecation warnings in 1.0, right, so maybe it's not a big deal?

**Comment by 1ucian0** [comment]
> That said, I think the hope is that there's no active deprecation warnings in 1.0, right, so maybe it's not a big deal?

I have the same hope. Let's re-evaluate for any deprecation warning stays in 1.0. Hopefully, none.

**Comment by Cryoris** [comment]
The tests seem to fail since there's a change in the deprecation message which now isn't captured by https://github.com/Qiskit/qiskit/blob/434897e0083756f21d3c154e45ea74802be9ac5b/qiskit/test/base.py#L248 
anymore (co-detective-d by @ElePT 🙂 )

**Review by kevinhartman — COMMENTED** [review]
LGTM once conflicts are resolved and `qiskit-terra` is updated to `qiskit` in the warning exemption that @Cryoris linked.

**Comment by jakelishman** [comment]
I'll take care of the merge conflicts on this PR, but we're going to merge this after the release of 0.45.0rc1.  This PR does not add any new deprecations, it just changes the default package name in the message emitted, and the default should only be being used internally within this library anyway (everything else should be setting `package_name` already, because they aren't Qiskit or Terra).

**Comment by 1ucian0** [comment]
> The tests seem to fail since there's a change in the deprecation message which now isn't captured by
> 
> https://github.com/Qiskit/qiskit/blob/434897e0083756f21d3c154e45ea74802be9ac5b/qiskit/test/base.py#L248
> 
> 
> anymore (co-detective-d by @ElePT 🙂 )

**Review by kevinhartman — APPROVED** [review]
LGTM.

Thanks for the updates @1ucian0!

**Pull request merged**
