### PR TITLE
Update random_circuit fuction in qiskit.circuit.random.utils.py 

### PR DESCRIPTION
**Pull request by PhysicsQoo**
### Summary

Adding random_clifford_T_circuit to support random circuits selects T and Tdg as elements.

### Details and comments
part of [#13053](https://github.com/Qiskit/qiskit/issues/13053)

### CODE REVIEW

**Comment by Cryoris** [comment]
Thanks for opening a PR @PhysicsQoo! But I think we could tackle your issue in a bit a more general fashion, I just left a comment on your issue.

**Comment by PhysicsQoo** [comment]
### **Description:**

Added a `gates: str | list[str] ='all'` argument, replacing the hardcoded gate list with `standard_gates.get_standard_gate_name_mapping()`.
Introduced a parameterized argument, allowing users to select whether they want parameterized rotation gates.

### **Known Issue:**

The parameterized functionality currently encounters an AttributeError: 'Parameter' object has no attribute '_root_uuid'. This issue is yet to be resolved.
The feature works correctly when parameterized = False.

**Comment by Cryoris** [comment]
Dear @PhysicsQoo, it's nice to see that you're motivated to implement the additions to the random circuit -- but we have to approach this a bit differently: for this PR, we cannot remove existing functionality.

We can do the following steps:
* Start by only adding support for an _additional_ `gates` argument in the `random_circuit` function. All other arguments remain in place, and we have to add the argument at the end (to not break user code that was using arguments positionally). So the new signature would be
    ```python
        def random_circuit(
        num_qubits,
        depth,
        max_operands=4,
        measure=False,
        conditional=False,
        reset=False,
        seed=None,
        num_operand_distribution: dict = None,
        gates=None,
    ):
    ```
* Then, instead of the hardcoded lists `gates_(1,2,3,4)q` we would like to use the `get_standard_gate_name_mapping` function. 
* If `gates` was given by the user, we can then filter to have only the supported gates.

Importantly, we don't change any of the existing functionality that creates the circuit with a certain depth or handles the operand distribution or parameterization. In a next step, we can have a look at supporting also `num_gates` as termination criterion or other features, but it would be good to start with a single feature and understand the process 🙂

**Comment by 1ucian0** [comment]
In its current state, this PR is a breaking change that do not follow the deprecation policy. I would close it for now. @PhysicsQoo please feel free to reopen a PR to address the @Cryoris comments.

**Pull request closed without merging**
