### PR TITLE
Adjust graphviz options for better layout with plot_gate_map()

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit fixes an issue with the visualizations of some backends/coupling maps. The default neato settings worked well in most cases but for some graphs it was not generating a good layout. This tweaks the settings a bit so that layouts work with more classes of graphs.

### Details and comments

### CODE REVIEW

**Comment by 1ucian0** [comment]
`ibm_fez`
image

**Comment by mtreinish** [comment]
Based on that image I'm wondering if we want to scale up the fontsize a bit?

**Comment by 1ucian0** [comment]
`ibm_quebec`

image

**Comment by mtreinish** [comment]
That second example looks like we should condition:

https://github.com/Qiskit/qiskit/pull/12770/files#diff-ff70fb816cde3f453d870891f47ede8245855a9e156228201a53fd613ad00659R1096-R1100

on `if not qubit_coordinates` and only use these graph attributes if we're doing an algorithmic layout.

**Comment by 1ucian0** [comment]
In the last change, I changed to prism and I got the following results:

`ibm_fez`
image

`ibm_cusconazca`
image

`ibm_torino`
image

`ibm_kyiv`
image

If you are happy when them, I will update the image references and merge.

**Comment by mtreinish** [comment]
> If you are happy when them, I will update the image references and merge.

Those look fine to me, the `ibm_torino` one is maybe a bit less pretty than `ibm_fez` and `ibm_cusconazca` but it looks fine. So let's just go with this.

**Comment by ElePT** [comment]
It looks like the font size still needs some tweaking:

1_qubit_gate_map
5_qubit_gate_map
16_qubit_gate_map

**Comment by 1ucian0** [comment]
Here, another round of changes:
image
image
image
image
image
image
image
image
image

**Comment by 1ucian0** [comment]
image
image
image
image
image
image
image
image
image

**Review by Cryoris — APPROVED** [review]
Thanks for the final tweaks @1ucian0 !

**Pull request merged**
