### PR TITLE
Add BasePrimitiveOptions

### PR DESCRIPTION
**Pull request by ikkoham**
### Summary

Based on https://github.com/Qiskit/RFCs/blob/c5d6ac069b50f6dc21f7715df8d1c5c2fede75e7/0018-primitive-options-type.md and https://github.com/Qiskit/qiskit/pull/11227#discussion_r1407939970.

### CODE REVIEW

**Comment by t-imamichi** [comment]
Do we need a constructor such as `BasePrimitiveOptions(foo=1, bar="bar")`?

**Comment by t-imamichi** [comment]
Do we need `BasePrimitiveOptionLike` as #11227 has?

**Comment by ikkoham** [comment]
> Do we need a constructor such as BasePrimitiveOptions(foo=1, bar="bar")?

Since this is a base class, I assume it has no properties. Is the default constructor not sufficient?

> Do we need BasePrimitiveOptionLike as https://github.com/Qiskit/qiskit/pull/11227 has?

Do you want it for the reference implementation of SamplerV2? If so, I'll add it.

**Review by ihincks — COMMENTED** [review]
Thank you for introducing this PR. The main motivation for introducing a common options class for all primitive implementations to use was to gain a same-look-and-feel UX across primitives. I think to really achieve this, we would need the options class inside of qiskit to have all of the features that we want to introduce, instead of being a bare-bones base class. For this reason, I propose to shelve this idea until we arrive at a polished format in qiskit-ibm-runtime, which can then, maybe, be backported here. In particular, I think we need more tooling for determining whether options are unset or default, etc.

**Comment by ikkoham** [comment]
OK, but I am suggesting this simply because it is needed in the Statevector primitives (both estimator and sampler). But, it is not large, so if you want to copy and paste and implement it in each instead of inheriting it, that is fine.

**Pull request closed without merging**
