### PR TITLE
Remove already "removed" `FakeBackendV2`

### PR DESCRIPTION
**Pull request by ElePT**
### Summary
This PR fixes an oversight from #11376 where the `FakeBackendV2` base class was removed from the documentation and reported as removed without actually removing the source code for the class (the fact that there were two `FakeBackendV2` classes probably didn't help). I'm labeling it as `changelog:None` because this change doesn't affect the public API.

### Details and comments

On hold until a `qiskit-experiments` release that includes https://github.com/Qiskit-Extensions/qiskit-experiments/commit/428c9bcffe3905f9a7ec689abf57d9c83d80b467. This allow the corresponding `qiskit-neko` tests to pass.

### CODE REVIEW

**Comment by 1ucian0** [comment]
With https://github.com/Qiskit-Extensions/qiskit-experiments/pull/1420 merged, an `on hold` be removed?

**Comment by ElePT** [comment]
> With [Qiskit-Extensions/qiskit-experiments#1420](https://github.com/Qiskit-Extensions/qiskit-experiments/pull/1420) merged, an `on hold` be removed?

We would need qiskit-experiments to do a bugfix/patch release so that neko can pull the fix for its test. I'll ping them about it.

**Comment by ElePT** [comment]
The patch release of qiskit-experiments is out! The PR can now be merged.

**Review by mtreinish — APPROVED** [review]
I confirmed this is not in the docs anywhere and was just an oversight for removal in 1.0. Heh, but you really like to test the stability policy between this and https://github.com/Qiskit/qiskit/pull/12042#pullrequestreview-1961126984

**Pull request merged**
