### PR TITLE
Make main-branch Qiskit distribution report as dev version

### PR DESCRIPTION
**Pull request by jakelishman**
### Summary

This moves the `.dev0` pre-release version specifier from being part of the git-hash logic to being an inherent part of the distribution version.  The `qiskit/VERSION.txt` file is currently used for two very similar purposes: it identifies the version of (what will be) the `qiskit` _distribution_ on PyPI, and the `qiskit` Python package.

We currently have runtime logic on `import qiskit` to modify the version to append `.dev0+<hash>` if the source is in a git checkout, but this does not affect the distribution version (which is what `pip` reads, when doing things like `pip install git+<qiskit>@main`).  This causes problems for downstream projects wanting to proactively test against Qiskit `main`, where some of their dependencies have put in `qiskit<1.0` pins for the time being.

We don't want to require all downstream packages to relax their release pins until necessary and verified, but ~`1.0.0.dev0 < 1` in Python land, so moving the `.dev0` logic to be hardcoded in the distribution version as well should allow `pip` resolution to be overridden when a git dependency on Qiskit-main is used in a complete `pip install` command.~

> [!WARNING]
> While [the packaging guidelines](https://packaging.python.org/en/latest/specifications/version-specifiers) do say that "1.0.0.dev0 is less than 1.0.0" and things like `packaging.version` will confirm this using Python's built-in `<`, the trouble is that later down, when used in _requirements_, [`<` excludes pre-releases unless the RHS is a pre-release itself](https://packaging.python.org/en/latest/specifications/version-specifiers/#exclusive-ordered-comparison).

For the immediate term goal of getting Qiskit Experiments' testing working, which relies on `qiskit-dynamics`, which in turn (very validly) relies on `qiskit<1`, so installing Qiskit from main will cause a packaging conflict.  The only way I can see to get round this is to use the pip "feature" that environment resolution need not be consistent through multiple calls to `pip` install.  I guess that means we're going to have to do
```
pip install -c constraints.txt qiskit-experiments qiskit-dynamics [... all requirements ...]
pip uninstall -y qiskit-terra qiskit
pip install -U git+https://github.com/Qiskit/qiskit
```
which is obviously highly fragile, and _technically_ a broken environment.

### Details and comments

If this is accepted and something we want to keep doing in the future (imo we should), then we might want to tweak our release-process documentation to include it.

### CODE REVIEW

**Comment by jakelishman** [comment]
The QPY test failure is easy to fix, but I've just been testing more locally, and this doesn't actually completely fix the resolution issues I was seeing, so I need to debug a bit more.

**Comment by mtreinish** [comment]
TBH, if we were to go this route I'd probably prefer that we just start using something like setuptools-scm and set all the version strings dynamically based on the git repo.

**Comment by jakelishman** [comment]
Yeah, that's probably a better strategy, and something that'd be good to maybe look into.  That said, it doesn't actually solve the immediate problem, so I'm not super bothered about pushing this through quickly now.

**Comment by jakelishman** [comment]
Closing as not needed.

**Pull request closed without merging**
