### PR TITLE
Remove Bit.register and Bit.index

### LINKED ISSUE #10744: Remove Bit.register and Bit.index, deprecated in 0.17 (released on April 01, 2021)
There is code released 28 month ago that needs to be removed.
 - qiskit/circuit/bit.py:63 (`register`)
 - qiskit/circuit/bit.py:85 (`index`)
 
This includes:
- [ ] Remove deprecated code and tests (if they only check the deprecation raise)
- [ ] tag the PR as [`Changelog: Removal`](https://github.com/Qiskit/qiskit/labels/Changelog%3A%20Removal)
- [ ] create a release note in the category `upgrade:`. If you can include an example with an alternative for user to migrate to the new code, as this change might break users code.

### PR DESCRIPTION
**Pull request by 1ucian0**
### Summary

Fixes https://github.com/Qiskit/qiskit/issues/10744

### CODE REVIEW

**Review by jakelishman — COMMENTED** [review]
As it stands, this PR hasn't done the complete job; the `register` and `index` arguments from the constructor also need removing, as do most of the actual methods from the class.  It'll become almost a completely opaque object.  All the private attributes of the object would be deleted as well, since they're no longer necessary.

**Comment by 1ucian0** [comment]
Based on how complicated cleaning (see https://github.com/1ucian0/qiskit-terra/pull/44/) I think it is better to merge this before to warn others the API is changing.

**Review by jakelishman — COMMENTED** [review]
This needs a release note about the removal, but given we seem to be going the direction of getting rid of the public components and try to sort out the backend behaviour that we're still accidentally relying on after, the code changes seem complete.

**Comment by 1ucian0** [comment]
reno in 3f16114d2f593f128b5284187c4219e8a8be4258

**Review by jakelishman — APPROVED** [review]
Thanks!

**Comment by jakelishman** [comment]
For linking purposes: the work of trying to disentangle the inner `_index` and `_register` properties has moved to #11407.

**Pull request merged**
